"""Deterministic, evidence-linked Story Architecture contracts."""

from pastila_scout.editor.story.defaults import (
    CANONICAL_PATTERN_IDS,
    CANONICAL_PRINCIPLE_IDS,
    DEFAULT_STORY_ARCHITECTURE,
    default_story_architecture,
)
from pastila_scout.editor.story.fingerprint import (
    architecture_fingerprint,
    pattern_collection_fingerprint,
    pattern_selection_fingerprint,
    profile_guidance_fingerprint,
    risk_collection_fingerprint,
    story_plan_fingerprint,
    unit_collection_fingerprint,
)
from pastila_scout.editor.story.models import (
    STAGE_RANK,
    AudienceTakeaway,
    ConsequencePlan,
    ConsequenceType,
    ContextPlacementPlan,
    NarrativeFunction,
    NarrativeSpine,
    NarrativeStage,
    OpeningStrategy,
    PayoffType,
    SatirePlacementPlan,
    SecondaryAngle,
    StoryArchitecture,
    StoryArchitecturePlan,
    StoryArchitecturePrinciple,
    StoryArchitectureReadiness,
    StoryArchitectureRisk,
    StoryArchitectureRiskType,
    StoryOpeningPlan,
    StoryPattern,
    StoryPatternSelection,
    StoryPayoffPlan,
    StoryProfileGuidance,
    StoryTransition,
    StoryUnit,
    StoryUnitType,
    TransitionRelationshipType,
)
from pastila_scout.editor.story.readiness import determine_story_readiness
from pastila_scout.editor.story.render import (
    render_pattern_selection,
    render_story_architecture,
    render_story_plan,
)
from pastila_scout.editor.story.rules import (
    CANONICAL_STORY_ARCHITECTURE_RULES,
    StoryArchitectureRule,
)
from pastila_scout.editor.story.validator import (
    StoryArchitectureValidationError,
    validate_story_architecture,
    validate_story_plan,
)

__all__ = [
    "CANONICAL_PATTERN_IDS",
    "CANONICAL_PRINCIPLE_IDS",
    "CANONICAL_STORY_ARCHITECTURE_RULES",
    "DEFAULT_STORY_ARCHITECTURE",
    "STAGE_RANK",
    "AudienceTakeaway",
    "ConsequencePlan",
    "ConsequenceType",
    "ContextPlacementPlan",
    "NarrativeFunction",
    "NarrativeSpine",
    "NarrativeStage",
    "OpeningStrategy",
    "PayoffType",
    "SatirePlacementPlan",
    "SecondaryAngle",
    "StoryArchitecture",
    "StoryArchitecturePlan",
    "StoryArchitecturePrinciple",
    "StoryArchitectureReadiness",
    "StoryArchitectureRisk",
    "StoryArchitectureRiskType",
    "StoryArchitectureRule",
    "StoryArchitectureValidationError",
    "StoryOpeningPlan",
    "StoryPattern",
    "StoryPatternSelection",
    "StoryPayoffPlan",
    "StoryProfileGuidance",
    "StoryTransition",
    "StoryUnit",
    "StoryUnitType",
    "TransitionRelationshipType",
    "architecture_fingerprint",
    "default_story_architecture",
    "determine_story_readiness",
    "pattern_collection_fingerprint",
    "pattern_selection_fingerprint",
    "profile_guidance_fingerprint",
    "render_pattern_selection",
    "render_story_architecture",
    "render_story_plan",
    "risk_collection_fingerprint",
    "story_plan_fingerprint",
    "unit_collection_fingerprint",
    "validate_story_architecture",
    "validate_story_plan",
]
