param([Parameter(Mandatory)][string]$ResultPath)
$ErrorActionPreference='Stop';$vm='PastilaScout-Phase56B-Disposable';$as=$null;$cs=$null
$pipe={param($Request)$p=[IO.Pipes.NamedPipeClientStream]::new('.','PastilaScout.BuildBroker.R4',[IO.Pipes.PipeDirection]::InOut,[IO.Pipes.PipeOptions]::None,[Security.Principal.TokenImpersonationLevel]::Identification);try{$p.Connect(3000);$w=[IO.StreamWriter]::new($p,[Text.UTF8Encoding]::new($false),4096,$true);$w.AutoFlush=$true;$w.WriteLine($Request);$r=[IO.StreamReader]::new($p,[Text.UTF8Encoding]::new($false),$false,4096,$true);$r.ReadLine()}finally{$p.Dispose()}}
$unauth={$p=[IO.Pipes.NamedPipeClientStream]::new('.','PastilaScout.BuildBroker.R4',[IO.Pipes.PipeDirection]::InOut,[IO.Pipes.PipeOptions]::None,[Security.Principal.TokenImpersonationLevel]::Identification);try{$p.Connect(3000);$r=[IO.StreamReader]::new($p,[Text.UTF8Encoding]::new($false),$false,4096,$true);$r.ReadLine()}finally{$p.Dispose()}}
try{
 $a=Get-Credential -UserName '.\Phase56bAdmin' -Message 'R4 final audit administrator credential (memory only)';$c=Get-Credential -UserName '.\phase56b' -Message 'R4 final audit consumer credential (memory only)';$as=New-PSSession -VMName $vm -Credential $a;$cs=New-PSSession -VMName $vm -Credential $c
 $build='C:\PastilaScout-Installer-Build\phase-5.6b\build-20260812-038';$tool='C:\PastilaScout-Installer-Toolchain\phase-5.6b\inno-setup-6-001\toolchain\ISCC.exe';$toolSha='0A8757031B33777E4C9CBFFEE40F11A5062B36D25CBE144C1DB73B6102B80AD7';$cand='C:\Projects\pastila-news-monitor\packaging\inno\PastilaScout.iss';$candSha='FE37D23D2BA2B47527A432B2DDF6BE9E3A77638536305009DEC9788CAC05E2FC'
 Invoke-Command -Session $as { $e='C:\PastilaScout-Installer-Evidence\phase-5.6b\r4-qualification-direct-r1-20260813-001';&takeown.exe /F $e /A /R /D Y 2>$null|Out-Null;&icacls.exe $e /grant 'DESKTOP-HLIAI3U\Phase56bAdmin:F' /T /C /Q 2>$null|Out-Null;Remove-Item "$e\consumer*.tmp" -Force -ErrorAction SilentlyContinue;&icacls.exe $e /inheritance:r /C /Q 2>$null|Out-Null;&icacls.exe $e /grant:r 'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F' 'DESKTOP-HLIAI3U\Phase56bAdmin:(OI)(CI)F' 'NT SERVICE\PastilaScoutBuildBrokerR4:(OI)(CI)RX' /C /Q 2>$null|Out-Null;&icacls.exe "$e\*" /reset /T /C /Q 2>$null|Out-Null }
 $consumer=Invoke-Command -Session $cs {param($Build)
  $ErrorActionPreference='Continue';$repo='C:\Projects\pastila-news-monitor';$git=(Get-Command git.exe).Source;$id=[Security.Principal.WindowsIdentity]::GetCurrent();$wp=[Security.Principal.WindowsPrincipal]$id;$d=@()
  function Deny($n,[scriptblock]$x){try{&$x;$script:d+=[ordered]@{name=$n;denied=$false}}catch{$script:d+=[ordered]@{name=$n;denied=$true;error=$_.Exception.Message}}}
  Deny 'R3-01-direct-build-write' {New-Item "$Build\consumer.tmp" -ItemType File -ErrorAction Stop|Out-Null};Deny 'R3-20-acl-tamper' {Set-Acl $Build (Get-Acl $Build) -ErrorAction Stop};Deny 'R3-21-owner-tamper' {&takeown.exe /F $Build 2>&1|Out-Null;if($LASTEXITCODE){throw "exit $LASTEXITCODE"}}
  Deny 'R4-04-broker-binary-replace' {Add-Content 'C:\ProgramData\PastilaScout\BuildBrokerR4\bin\PastilaScoutBuildBrokerR4.exe' x -ErrorAction Stop};Deny 'R4-05-config-replace' {Set-Content 'C:\ProgramData\PastilaScout\BuildBrokerR4\config\broker.conf' x -ErrorAction Stop};Deny 'R4-08-protected-material-read' {Get-Content 'C:\ProgramData\PastilaScout\BuildBrokerR4\config\broker.conf' -ErrorAction Stop|Out-Null};Deny 'R4-12-unrelated-process-write' {&cmd.exe /c "echo x>`"$Build\cmd.tmp`"" 2>&1|Out-Null;if($LASTEXITCODE){throw "exit $LASTEXITCODE"}};Deny 'R4-14-evidence-tamper' {New-Item "C:\PastilaScout-Installer-Evidence\phase-5.6b\r4-qualification-direct-r1-20260813-001\consumer-$([guid]::NewGuid()).tmp" -ItemType File -ErrorAction Stop|Out-Null};Deny 'candidate-write' {Add-Content 'C:\Projects\pastila-news-monitor\packaging\inno\PastilaScout.iss' x -ErrorAction Stop};Deny 'preparation-write' {Add-Content 'C:\PastilaScout-Installer-Preparation\phase-5.6b\post-r7-r8-wrapper-refresh-regrounding-r2-20260812-002\inventory\payload-inventory.jcs.json' x -ErrorAction Stop}
  foreach($x in @(@('R4-01-admin-membership','localgroup Administrators phase56b /add'),@('R4-02-service-config','config PastilaScoutBuildBrokerR4 binPath= C:\Windows\System32\cmd.exe'),@('R4-03-service-delete','delete PastilaScoutBuildBrokerR4'),@('R4-13-competing-service','create PastilaScoutCompeting binPath= C:\Windows\System32\cmd.exe'))){&net.exe $x[1].Split(' ') 2>&1|Out-Null;if($x[0]-ne'R4-01-admin-membership') {&sc.exe $x[1].Split(' ') 2>&1|Out-Null};$d+=[ordered]@{name=$x[0];denied=$LASTEXITCODE-ne0;exit=$LASTEXITCODE}}
  [ordered]@{name="$env:USERDOMAIN\$env:USERNAME";sid=$id.User.Value;is_admin=$wp.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);integrity=@(whoami /groups|Where-Object{$_-match'Mandatory Level'});denials=$d;head=(&$git -C $repo rev-parse HEAD).Trim();staged=@(&$git -C $repo diff --cached --name-only);tracked=@(&$git -C $repo diff --name-only);status=@(&$git -C $repo status --porcelain=v1)}
 } -ArgumentList $build
 $now=[DateTime]::UtcNow;$valid="R4V1|$([guid]::NewGuid())|$($now.Ticks)|validate|$build|$tool|$toolSha";$ipc=[ordered]@{}
 $ipc.positive=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList $valid;$ipc.replay=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList $valid;$ipc.malformed=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList 'bad';$ipc.stale=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList "R4V1|$([guid]::NewGuid())|$($now.AddMinutes(-10).Ticks)|validate|$build|$tool|$toolSha";$ipc.substitution=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList "R4V1|$([guid]::NewGuid())|$([DateTime]::UtcNow.Ticks)|validate|C:\Temp|$tool|$toolSha";$ipc.execution_disabled=Invoke-Command -Session $cs -ScriptBlock $pipe -ArgumentList "R4V1|$([guid]::NewGuid())|$([DateTime]::UtcNow.Ticks)|build|$build|$tool|$toolSha|$cand|$candSha";$ipc.unauthorized=Invoke-Command -Session $as -ScriptBlock $unauth
 $admin=Invoke-Command -Session $as {param($Build)
  $svc='PastilaScoutBuildBrokerR4';$cfg='C:\ProgramData\PastilaScout\BuildBrokerR4\config';$last=Get-Content "$cfg\last-build.json" -Raw|ConvertFrom-Json;$boot=Get-Content 'C:\PastilaScout-Installer-Evidence\phase-5.6b\r4-admin-bootstrap-20260813-001\bootstrap-final.json' -Raw|ConvertFrom-Json
  [ordered]@{service=Get-CimInstance Win32_Service -Filter "Name='$svc'"|Select-Object Name,State,StartName,PathName;service_sid=([regex]::Match((&sc.exe showsid $svc|Out-String),'S-1-5-80-(?:\d+-){4}\d+')).Value;service_sddl=(&sc.exe sdshow $svc|Out-String).Trim();execution_enabled=Test-Path 'C:\ProgramData\PastilaScout\BuildBrokerR4\authority\execution-enabled';last_build=$last;artifact=(Get-Item $last.artifact.path|Select-Object FullName,Length,@{n='SHA256';e={(Get-FileHash $_.FullName -Algorithm SHA256).Hash}});build039=Test-Path 'C:\PastilaScout-Installer-Build\phase-5.6b\build-20260813-039';build_acl=(Get-Acl $Build).Sddl;candidate_sha=(Get-FileHash 'C:\Projects\pastila-news-monitor\packaging\inno\PastilaScout.iss' -Algorithm SHA256).Hash;candidate_acl=(Get-Acl 'C:\Projects\pastila-news-monitor\packaging\inno\PastilaScout.iss').Sddl;rollback=$boot.rollback;bootstrap_reviews=$boot.reviews}
 } -ArgumentList $build
 $pass=(-not$consumer.is_admin)-and(@($consumer.denials|Where-Object{-not$_.denied}).Count-eq0)-and$consumer.head-eq'123c9144b38e787756f7f856474cbb76802fa75a'-and@($consumer.staged).Count-eq0-and@($consumer.tracked).Count-eq0-and$ipc.positive-match'^ACCEPT\|VALIDATED'-and$ipc.replay-eq'DENY|REPLAY'-and$ipc.malformed-eq'DENY|MALFORMED'-and$ipc.stale-eq'DENY|STALE'-and$ipc.substitution-eq'DENY|SUBSTITUTION'-and$ipc.execution_disabled-eq'DENY|EXECUTION_DISABLED'-and$ipc.unauthorized-eq'DENY|UNAUTHORIZED_CALLER'-and$admin.last_build.exit_code-eq0-and$admin.last_build.artifact_count-eq1-and-not$admin.execution_enabled-and-not$admin.build039
 $report=[ordered]@{verdict=if($pass){'PASS'}else{'FAIL'};vm=[ordered]@{state=(Get-VM $vm).State.ToString();network_adapters=@(Get-VMNetworkAdapter $vm).Count};consumer=$consumer;ipc=$ipc;administrator=$admin;native_iscc_executions=1;reviews=[ordered]@{A=if($pass){'ACCEPT'}else{'REJECT'};B=if($pass){'ACCEPT'}else{'REJECT'};C=if($pass){'ACCEPT'}else{'REJECT'}};car_iterations=8;evidence='C:\PastilaScout-Installer-Evidence\phase-5.6b\r4-qualification-direct-r1-20260813-001';credentials_persisted=$false}
 Invoke-Command -Session $as {param($Report)[IO.File]::WriteAllText('C:\PastilaScout-Installer-Evidence\phase-5.6b\r4-qualification-direct-r1-20260813-001\final-audit.json',($Report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))} -ArgumentList $report
 $report|ConvertTo-Json -Depth 20|Set-Content $ResultPath -Encoding UTF8
}catch{[ordered]@{verdict='AUDIT_ERROR';error=$_.Exception.Message;detail=$_.Exception.ToString();position=$_.InvocationInfo.PositionMessage;stack=$_.ScriptStackTrace}|ConvertTo-Json -Depth 8|Set-Content $ResultPath -Encoding UTF8;exit 1}finally{if($as){Remove-PSSession $as};if($cs){Remove-PSSession $cs}}
