import json
from pathlib import Path


ROOT=Path(__file__).resolve().parents[1]
DESIGN=ROOT/"docs/artifacts/semantic-admission-v2-stage-p-timeout-lifecycle-remediation-design-v1.json"


def _design(): return json.loads(DESIGN.read_text("utf-8"))


def test_design_does_not_overclaim_runner_phase_or_semantic_result() -> None:
    design=_design(); unknown=" ".join(design["not_established"])
    assert "Whether either timed-out runner completed" in unknown
    assert design["design_conclusion"].startswith("Do not adjust the timeout first")


def test_durable_lifecycle_survives_temp_cleanup_and_records_progress() -> None:
    requirements=" ".join(_design()["remediation_stage_1_durable_observability"]["requirements"])
    assert "outside every TemporaryDirectory" in requirements
    assert "GENERATION_HEARTBEAT" in requirements and "partial generated bytes" in requirements
    assert "never parsed as complete" in requirements


def test_incremental_candidate_requires_exact_equivalence_and_safe_rebuild() -> None:
    stage=_design()["remediation_stage_2_zero_inference_performance_characterization"]
    requirements=" ".join(stage["requirements"]);acceptance=" ".join(stage["acceptance"])
    assert "byte-exactly extends" in requirements and "rebuild" in requirements
    assert "Zero allowed-token-set divergences" in acceptance
    assert stage["model_load"] is stage["inference"] is False


def test_no_timeout_prompt_schema_or_runtime_change_is_authorized() -> None:
    design=_design();prohibited=" ".join(design["remediation_stage_3_candidate_boundaries"]["prohibited_without_new_design_authority"])
    assert "Do not increase timeout" in prohibited
    assert "No prompt, schema" in prohibited
    assert all(value is False for value in design["authority"].values())


def test_rerun_sequence_starts_with_stage_p_only_and_needs_fresh_authority() -> None:
    sequence=" ".join(_design()["verification_sequence_before_any_proof_rerun"])
    assert "Stage-P-only Case 01" in sequence
    assert "unused calls from failed Run 1 are not reusable authority" in sequence
