"""Provider-neutral execution architecture for Module 2.9 Phase 7.1."""

from .authority import (
    build_provider_descriptor,
    build_provider_request_envelope,
    build_provider_result_envelope,
    validate_provider_descriptor,
    validate_provider_request_envelope,
    validate_provider_result_envelope,
)
from .errors import (
    DuplicateProviderRegistrationError,
    InvalidProviderAdapterError,
    InvalidProviderDescriptorError,
    InvalidProviderIdentifierError,
    ProviderCapabilityUnavailableError,
    ProviderV2ValidationError,
    UnknownProviderError,
)
from .identity import (
    descriptor_fingerprint,
    descriptor_identity,
    request_envelope_fingerprint,
    request_envelope_identity,
    request_message_fingerprint,
    request_message_identity,
    request_unit_fingerprint,
    request_unit_identity,
    result_envelope_fingerprint,
    result_envelope_identity,
    result_unit_fingerprint,
    result_unit_identity,
)
from .interface import ProviderAdapter
from .models import (
    ProviderCapabilityV2,
    ProviderDescriptorV2,
    ProviderFinishReasonV2,
    ProviderMessageInputV2,
    ProviderOutputInputV2,
    ProviderRequestEnvelopeV2,
    ProviderRequestIntentV2,
    ProviderRequestMessageV2,
    ProviderRequestUnitInputV2,
    ProviderRequestUnitV2,
    ProviderResultEnvelopeV2,
    ProviderResultProjectionV2,
    ProviderResultStatusV2,
    ProviderResultUnitV2,
    ProviderV2ValidationIssue,
)
from .registry import ProviderRegistry

__all__ = (
    "DuplicateProviderRegistrationError",
    "InvalidProviderAdapterError",
    "InvalidProviderDescriptorError",
    "InvalidProviderIdentifierError",
    "ProviderAdapter",
    "ProviderCapabilityUnavailableError",
    "ProviderCapabilityV2",
    "ProviderDescriptorV2",
    "ProviderFinishReasonV2",
    "ProviderMessageInputV2",
    "ProviderOutputInputV2",
    "ProviderRegistry",
    "ProviderRequestEnvelopeV2",
    "ProviderRequestIntentV2",
    "ProviderRequestMessageV2",
    "ProviderRequestUnitInputV2",
    "ProviderRequestUnitV2",
    "ProviderResultEnvelopeV2",
    "ProviderResultProjectionV2",
    "ProviderResultStatusV2",
    "ProviderResultUnitV2",
    "ProviderV2ValidationError",
    "ProviderV2ValidationIssue",
    "UnknownProviderError",
    "build_provider_descriptor",
    "build_provider_request_envelope",
    "build_provider_result_envelope",
    "descriptor_fingerprint",
    "descriptor_identity",
    "request_envelope_fingerprint",
    "request_envelope_identity",
    "request_message_fingerprint",
    "request_message_identity",
    "request_unit_fingerprint",
    "request_unit_identity",
    "result_envelope_fingerprint",
    "result_envelope_identity",
    "result_unit_fingerprint",
    "result_unit_identity",
    "validate_provider_descriptor",
    "validate_provider_request_envelope",
    "validate_provider_result_envelope",
)
