"""Immutable ASCII Romanian resources for the desktop shell."""

from pastila_scout import __version__

from .errors import _DesktopShellConfigurationError

_TEXT_V1 = (
    ("app.title", "Pastila Scout"),
    ("menu.file", "Fisier"),
    ("menu.file.exit", "Iesire"),
    ("menu.view", "Vizualizare"),
    ("menu.view.scout", "Scout"),
    ("menu.view.editor", "Editor"),
    ("menu.help", "Ajutor"),
    ("menu.help.about", "Despre"),
    ("menu.help.check_updates", "Cauta actualizari"),
    ("navigation.scout", "Scout"),
    ("navigation.editor", "Editor"),
    ("navigation.chief_editor", "Chief Editor"),
    ("scout.period", "Perioada"),
    ("scout.category", "Categorie"),
    ("scout.latest", "Ultima Ora"),
    ("scout.provider", "AI Engine"),
    ("scout.ollama_url", "Adresa Ollama"),
    ("scout.ollama_model", "Model Ollama"),
    ("scout.model", "Model"),
    ("scout.provider_save", "Salveaza AI Engine"),
    ("scout.provider_test", "Testeaza conexiunea"),
    ("scout.provider_saved", "AI Engine a fost salvat."),
    ("scout.ollama_ready", "Ollama si modelul configurat sunt disponibile."),
    ("scout.ollama_unavailable", "Ollama sau modelul configurat nu este disponibil."),
    ("scout.source_add", "Adauga sursa"),
    ("scout.source_save", "Salveaza sursa"),
    (
        "scout.source_saved",
        "Sursa a fost salvata si va fi folosita la rularile viitoare.",
    ),
    ("scout.source_duplicate", "Sursa exista deja."),
    ("scout.source_invalid", "Introdu o adresa HTTP sau HTTPS valida."),
    ("scout.source_unsupported", "Sursa nu este un flux RSS sau Atom compatibil."),
    ("scout.run", "Cauta"),
    ("scout.sources_available", "Surse disponibile"),
    ("scout.results", "Rezultate cautare"),
    ("scout.intro", "Selectati optiunile dorite, apoi apasati Cauta."),
    ("scout.progress.reading", "Pastila citeste ziarele..."),
    ("scout.progress.verifying", "verifica si compara..."),
    ("scout.progress.writing", "scrie raportul..."),
    ("scout.progress.ready", "Raportul este pregatit."),
    ("scout.failed_sources", "Surse cu erori"),
    ("scout.report", "Deschide raportul"),
    ("scout.send_editor", "Trimite in Editor"),
    ("scout.no_candidates", "Nu exista materiale Scout disponibile."),
    ("scout.handoff_success", "Materialul a fost trimis in Editor."),
    ("scout.handoff_many", "{count} materiale au fost trimise in Editor."),
    ("scout.handoff_duplicates", " {count} duplicate au fost omise."),
    ("scout.handoff_failure", "Materialele nu au putut fi trimise in Editor."),
    ("editor.title", "Editor"),
    ("editor.active_project", "Stire selectata"),
    ("editor.worklist.story", "Stire"),
    ("editor.worklist.status", "Status"),
    ("editor.worklist.pending", "In asteptare"),
    ("editor.worklist.running", "In procesare"),
    ("editor.worklist.completed", "Generata"),
    ("editor.worklist.failed", "Eroare"),
    ("editor.unavailable", "Editorul va fi disponibil intr-o etapa ulterioara."),
    ("editor.scout_input", "Intrare Scout"),
    ("editor.selection_profile", "Profil de selectie"),
    ("editor.episode_context", "Context episod"),
    ("editor.generation_config", "Configuratie generare"),
    ("editor.provider", "AI Engine"),
    ("editor.model", "Model"),
    ("editor.timeout", "Timp-limita (secunde)"),
    ("editor.output", "Fisier de iesire"),
    ("editor.no_replace", "Nu inlocui fisierul existent"),
    ("editor.run", "Genereaza"),
    ("editor.retry", "Reincearca"),
    ("editor.configuration_required", "Configuratia Editor nu este completa."),
    ("chief_editor.title", "Titlu episod / proiect"),
    ("chief_editor.section", "Sectiune"),
    ("chief_editor.note", "Nota / tranzitie"),
    ("chief_editor.up", "Sus"),
    ("chief_editor.add", "Adauga"),
    ("chief_editor.down", "Jos"),
    ("chief_editor.remove", "Elimina din structura"),
    ("chief_editor.save", "Salveaza"),
    ("chief_editor.export", "Exporta structura"),
    ("chief_editor.empty", "Nu exista materiale dezvoltate in Editor."),
    ("chief_editor.saved", "Structura Chief Editor a fost salvata."),
    ("about.title", "Despre Pastila Scout"),
    ("about.body", "Pastila Scout"),
    ("about.version", __version__),
    ("close.running", "Inchidere in curs..."),
    ("error.internal", "Aplicatia a intampinat o eroare interna."),
    ("startup.error", "Aplicatia nu a putut fi configurata."),
    ("state.error", "Starea aplicatiei Windows nu a putut fi initializata."),
    ("migration.title", "Importa starea de dezvoltare"),
    (
        "migration.prompt",
        "Selectati un proiect de dezvoltare pentru import. Fisierele sursa nu vor fi sterse.",
    ),
    ("migration.confirm", "Importati starea validata in profilul Windows?"),
    ("migration.error", "Starea de dezvoltare nu a putut fi importata."),
    ("sources.override.error", "Configuratia surselor personalizate este invalida."),
    ("setup.title", "Configurare Pastila Scout"),
    (
        "setup.intro",
        "Alege AI Engine si verifica pregatirea pentru utilizarea zilnica.",
    ),
    (
        "setup.no_sources",
        "Activeaza cel putin o sursa Scout in configuratia existenta.",
    ),
    (
        "setup.openai_missing",
        "Cheia OpenAI nu este disponibila prin mecanismul existent.",
    ),
    ("setup.openai_local", "OpenAI este verificat local, fara apel si fara cost."),
    ("setup.ollama_test_required", "Testeaza conexiunea Ollama inainte de continuare."),
    ("setup.ollama_no_models", "Ollama este disponibil, dar nu are modele instalate."),
    ("setup.invalid", "Configuratia nu este valida. Verifica AI Engine si modelul."),
    ("setup.continue", "Salveaza si continua"),
)
_LOOKUP = dict(_TEXT_V1)
if len(_LOOKUP) != len(_TEXT_V1):
    raise RuntimeError("Duplicate desktop resource key")


def _text_v1(*, key: str) -> str:
    if type(key) is not str or key not in _LOOKUP:
        raise _DesktopShellConfigurationError() from None
    return _LOOKUP[key]
