"""Public immutable M6C.6B execution-dispatch contract and resolution API."""

from .architecture import CorrectiveActionExecutionDispatchDescriptor
from .bindings import (
    CorrectiveActionExecutorBinding,
    CorrectiveActionExecutorBindings,
    validate_executor_binding,
    validate_executor_bindings,
)
from .composition import (
    CorrectiveActionExecutionDispatchWorkflowDescriptor,
    CorrectiveActionExecutionDispatchWorkflowOutcome,
    CorrectiveActionExecutionDispatchWorkflowRequest,
    CorrectiveActionExecutionDispatchWorkflowResult,
    CorrectiveActionExecutionDispatchWorkflowService,
    dispatch_corrective_action_execution,
    validate_execution_dispatch_workflow_request,
    validate_execution_dispatch_workflow_result,
)
from .contracts import CorrectiveActionExecutor
from .dispatcher import CorrectiveActionExecutionDispatcher, DispatchRuntimeResult
from .eligibility import (
    DispatchEligibilityEvaluator,
    DispatchEligibilityReport,
    DispatchEligibilityResult,
    DispatchEligibilityStatus,
    build_dispatch_eligibility_report,
    validate_dispatch_eligibility_result,
)
from .enums import (
    CorrectiveActionAuthorizationState,
    CorrectiveActionExecutionDispatchDiagnosticCategory,
    CorrectiveActionExecutionDispatchDiagnosticCode,
    CorrectiveActionExecutionDispatchOutcome,
    CorrectiveActionExecutionDispatchStatus,
    CorrectiveActionExecutionStatus,
    CorrectiveActionExecutorOutcome,
)
from .input_transport import (
    CorrectiveActionExecutorRequestV2,
    build_corrective_action_executor_request_v2,
    build_executor_request_v2_report,
    serialize_executor_request_v2_report,
    validate_executor_request_v2,
)
from .models import (
    CorrectiveActionExecutionContext,
    CorrectiveActionExecutionDispatchDiagnostic,
    CorrectiveActionExecutionDispatchPolicy,
    CorrectiveActionExecutionDispatchReport,
    CorrectiveActionExecutionDispatchRequest,
    CorrectiveActionExecutionDispatchResult,
    CorrectiveActionExecutorDescriptor,
    CorrectiveActionExecutorRequest,
    CorrectiveActionExecutorResult,
    CorrectiveActionOutputReference,
)
from .policy import build_standard_corrective_action_execution_dispatch_policy
from .registry import (
    CorrectiveActionExecutorRegistry,
    CorrectiveActionExecutorRegistryReport,
    build_executor_registry_report,
    validate_executor_registry,
)
from .reporting import (
    build_execution_dispatch_report,
    render_execution_dispatch_report,
    serialize_execution_dispatch_report,
)
from .resolution import (
    CapabilityResolutionDiagnosticCode,
    CapabilityResolutionReport,
    CapabilityResolutionResult,
    CapabilityResolutionStatus,
    CapabilityResolver,
    build_capability_resolution_report,
    validate_capability_resolution_result,
)
from .resolution_reporting import (
    render_capability_resolution_report,
    render_dispatch_eligibility_report,
    render_executor_registry_report,
    serialize_capability_resolution_report,
    serialize_dispatch_eligibility_report,
    serialize_executor_registry_report,
)
from .runtime_reporting import (
    CorrectiveActionExecutionDispatchRuntimeReport,
    build_execution_dispatch_runtime_report,
    render_execution_dispatch_runtime_report,
    serialize_execution_dispatch_runtime_report,
)
from .service import (
    CorrectiveActionExecutionDispatchService,
    build_standard_corrective_action_execution_dispatch_service,
)
from .state import (
    CorrectiveActionExecutionDispatchEvent,
    CorrectiveActionExecutionDispatchPhase,
    CorrectiveActionExecutionDispatchState,
    transition_dispatch_state,
    validate_dispatch_state,
)
from .v2_runtime import (
    CorrectiveActionExecutionDispatcherV2,
    CorrectiveActionExecutionPhaseV2,
    CorrectiveActionExecutionResponse,
    CorrectiveActionExecutionResponseStatus,
    CorrectiveActionExecutionSafeReport,
    CorrectiveActionV2Binding,
    build_execution_safe_report,
    serialize_execution_safe_report,
    validate_execution_response,
)
from .validation import (
    validate_execution_context,
    validate_execution_dispatch_diagnostic,
    validate_execution_dispatch_policy,
    validate_execution_dispatch_request,
    validate_execution_dispatch_result,
    validate_executor_descriptor,
    validate_executor_request,
    validate_executor_result,
)

__all__ = [
    "CapabilityResolutionDiagnosticCode",
    "CapabilityResolutionReport",
    "CapabilityResolutionResult",
    "CapabilityResolutionStatus",
    "CapabilityResolver",
    "CorrectiveActionAuthorizationState",
    "CorrectiveActionExecutionContext",
    "CorrectiveActionExecutionDispatchDescriptor",
    "CorrectiveActionExecutionDispatchDiagnostic",
    "CorrectiveActionExecutionDispatchDiagnosticCategory",
    "CorrectiveActionExecutionDispatchDiagnosticCode",
    "CorrectiveActionExecutionDispatchEvent",
    "CorrectiveActionExecutionDispatchOutcome",
    "CorrectiveActionExecutionDispatchPhase",
    "CorrectiveActionExecutionDispatchPolicy",
    "CorrectiveActionExecutionDispatchReport",
    "CorrectiveActionExecutionDispatchRequest",
    "CorrectiveActionExecutionDispatchResult",
    "CorrectiveActionExecutionDispatchRuntimeReport",
    "CorrectiveActionExecutionDispatchService",
    "CorrectiveActionExecutionDispatchState",
    "CorrectiveActionExecutionDispatchStatus",
    "CorrectiveActionExecutionDispatchWorkflowDescriptor",
    "CorrectiveActionExecutionDispatchWorkflowOutcome",
    "CorrectiveActionExecutionDispatchWorkflowRequest",
    "CorrectiveActionExecutionDispatchWorkflowResult",
    "CorrectiveActionExecutionDispatchWorkflowService",
    "CorrectiveActionExecutionDispatcher",
    "CorrectiveActionExecutionDispatcherV2",
    "CorrectiveActionExecutionPhaseV2",
    "CorrectiveActionExecutionResponse",
    "CorrectiveActionExecutionResponseStatus",
    "CorrectiveActionExecutionSafeReport",
    "CorrectiveActionExecutionStatus",
    "CorrectiveActionExecutor",
    "CorrectiveActionExecutorBinding",
    "CorrectiveActionExecutorBindings",
    "CorrectiveActionExecutorDescriptor",
    "CorrectiveActionExecutorOutcome",
    "CorrectiveActionExecutorRegistry",
    "CorrectiveActionExecutorRegistryReport",
    "CorrectiveActionExecutorRequest",
    "CorrectiveActionExecutorRequestV2",
    "CorrectiveActionExecutorResult",
    "CorrectiveActionOutputReference",
    "CorrectiveActionV2Binding",
    "DispatchEligibilityEvaluator",
    "DispatchEligibilityReport",
    "DispatchEligibilityResult",
    "DispatchEligibilityStatus",
    "DispatchRuntimeResult",
    "build_capability_resolution_report",
    "build_corrective_action_executor_request_v2",
    "build_dispatch_eligibility_report",
    "build_execution_dispatch_report",
    "build_execution_dispatch_runtime_report",
    "build_execution_safe_report",
    "build_executor_registry_report",
    "build_executor_request_v2_report",
    "build_standard_corrective_action_execution_dispatch_policy",
    "build_standard_corrective_action_execution_dispatch_service",
    "dispatch_corrective_action_execution",
    "render_capability_resolution_report",
    "render_dispatch_eligibility_report",
    "render_execution_dispatch_report",
    "render_execution_dispatch_runtime_report",
    "render_executor_registry_report",
    "serialize_capability_resolution_report",
    "serialize_dispatch_eligibility_report",
    "serialize_execution_dispatch_report",
    "serialize_execution_dispatch_runtime_report",
    "serialize_execution_safe_report",
    "serialize_executor_registry_report",
    "serialize_executor_request_v2_report",
    "transition_dispatch_state",
    "validate_capability_resolution_result",
    "validate_dispatch_eligibility_result",
    "validate_dispatch_state",
    "validate_execution_context",
    "validate_execution_dispatch_diagnostic",
    "validate_execution_dispatch_policy",
    "validate_execution_dispatch_request",
    "validate_execution_dispatch_result",
    "validate_execution_dispatch_workflow_request",
    "validate_execution_dispatch_workflow_result",
    "validate_execution_response",
    "validate_executor_binding",
    "validate_executor_bindings",
    "validate_executor_descriptor",
    "validate_executor_registry",
    "validate_executor_request",
    "validate_executor_request_v2",
    "validate_executor_result",
]
