#!/usr/bin/env python3
import argparse,copy,hashlib,json
from pathlib import Path
ACTIVE_ID='5a5988bd0fb3b7d760c5a99dd13c007281a6900dd6a572c21c3812d6cd00bf93';ACTIVE_SHA='6c79a7e25b22c80caad93a05b6701860166e3af88626a543fc3aa9c38ed761ee';ACTIVE_RECEIPT='94315f47066ef8936d13c8dc8ddcbf7db063a723bb7618839bb9844ab077419d';ACTIVE_AUTH='7fce03be563e737021a61d4804aa8c1c5e68e38406525c59b4130a4e50715f9a'
IMMEDIATE_ROOT='/root/pastila-vnext/.rollback-pre-attestation-5a5988bd';IMMEDIATE_ID='6deeb96a788f3780835a9dce3583153e53ab6c6121ddea994495e4c9cc8e1a9f';IMMEDIATE_SHA='67dead9fd542da9464fc798a7037fb15b4c5f8270c626c9e0ce41f58265a74ff'
HISTORICAL_ROOT='/root/pastila-vnext/.rollback-pre-gui-4d45f169';HISTORICAL_ID='278df8cdd27f641a44fd7941bfc89c362dcb5af3f1a9f265148fa11c85e44ab0';HISTORICAL_SHA='c9c6b9bb60c881781b1b534990bc37b76a7e012f2599144e2656984854f5fa58'
PRIOR_ROOT='/root/pastila-vnext/.rollback-pre-contract-e180a1e5';PRIOR_ID='03e43da4e052ed0bf0a1caa7f9da7103a111e1192362ea9887ed86388b864b78';PRIOR_SHA='196c5f7bdec6f59f0609ad334dbdebdc17e5ad9f793945713ff2b7afaa5b58a2'
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ident(v):return hashlib.sha256(canon(v)).hexdigest()
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for c in iter(lambda:f.read(8388608),b''):h.update(c)
 return h.hexdigest()
def write(p,v,k):v.pop(k,None);v[k]=ident(v);p.write_text(json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def row(p,target):return {'path':target,'type':'file','size':p.stat().st_size,'sha256':sha(p)}
def build(repo,active,immediate,historical,prior,out):
 roots=[active,immediate,historical,prior];locks=[json.loads((x/'product-lock.json').read_text()) for x in roots];expected=[(ACTIVE_ID,ACTIVE_SHA),(IMMEDIATE_ID,IMMEDIATE_SHA),(HISTORICAL_ID,HISTORICAL_SHA),(PRIOR_ID,PRIOR_SHA)]
 for root,lock,(identity,digest) in zip(roots,locks,expected):
  if lock.get('product_lock_identity')!=identity or sha(root/'product-lock.json')!=digest:raise RuntimeError('root identity '+str(root))
 cur,direct,old,older=locks;receipt0=json.loads((active/'manifest/activation/vnext-activation-receipt-v1.json').read_text());auth0=json.loads((active/'manifest/authorities/vnext-active-product-lock-successor-v1.json').read_text())
 if receipt0['activation_receipt_identity']!=ACTIVE_RECEIPT or auth0['active_state_authority_identity']!=ACTIVE_AUTH:raise RuntimeError('active authority')
 out.mkdir(parents=True,exist_ok=True)
 historical_roots=[{'path':HISTORICAL_ROOT,'classification':'HISTORICAL_NON_CANONICAL','product_lock_identity':HISTORICAL_ID,'product_lock_sha256':HISTORICAL_SHA},{'path':PRIOR_ROOT,'classification':'HISTORICAL_NON_CANONICAL_PENDING_RETIREMENT','product_lock_identity':PRIOR_ID,'product_lock_sha256':PRIOR_SHA}]
 manifest={'schema':'vnext-gui-attestation-canonical-rollback-manifest-v5','schema_version':5,'status':'PASS_CANONICAL_FACTUAL_IMMEDIATE_PREDECESSOR','rollback_root':IMMEDIATE_ROOT,'authority':{'product_lock_identity':IMMEDIATE_ID,'product_lock_sha256':IMMEDIATE_SHA},'verification':{'managed_inventory_source':'product-lock.json','managed_file_count':len(direct['application_files']),'active_graph_identity':direct['active_graph_identity'],'prospective_atomic_rollback':'PASS','prospective_restore':'PASS'},'historical_roots':historical_roots,'legacy_dependency_count':0};write(out/'vnext-gui-attestation-canonical-rollback-manifest-v5.json',manifest,'rollback_manifest_identity')
 receipt=copy.deepcopy(receipt0);receipt.pop('activation_receipt_identity',None);receipt.update(schema='vnext-gui-current-activation-receipt-v2',schema_version=2,status='ATTESTED_CURRENT_ACTIVATION_CANONICAL_ROLLBACK_RECONCILED',predecessor_activation_receipt_identity=ACTIVE_RECEIPT);receipt['rollback']={'canonical_root':IMMEDIATE_ROOT,'canonical_product_lock_identity':IMMEDIATE_ID,'canonical_product_lock_sha256':IMMEDIATE_SHA,'manifest_identity':manifest['rollback_manifest_identity'],'historical_roots':historical_roots};write(out/'vnext-gui-current-activation-receipt-v2.json',receipt,'activation_receipt_identity')
 authority={'schema':'vnext-gui-current-active-state-authority-v2','schema_version':2,'status':'ACTIVATED_ATTESTED_CANONICAL_FACTUAL_IMMEDIATE_PREDECESSOR','active_root':'/root/pastila-vnext/v1','installed_product_lock':{'identity':ACTIVE_ID,'sha256':ACTIVE_SHA},'predecessor_active_state_authority_identity':ACTIVE_AUTH,'activation_candidate_product_lock_identity':cur['activation_attestation']['activation_candidate_product_lock_identity'],'activation_receipt_identity':receipt['activation_receipt_identity'],'active_graph_identity':cur['active_graph_identity'],'active_authority_surface_identity':auth0['active_authority_surface_identity'],'post_install_audit_identity':auth0['post_install_audit_identity'],'canonical_rollback':{'manifest_identity':manifest['rollback_manifest_identity'],'root':IMMEDIATE_ROOT,'product_lock_identity':IMMEDIATE_ID,'product_lock_sha256':IMMEDIATE_SHA},'historical_roots':historical_roots,'voice':'DISABLED_UNTIL_PROMOTION','legacy_dependency_count':0};write(out/'vnext-gui-current-active-state-authority-v2.json',authority,'active_state_authority_identity')
 successor=copy.deepcopy(cur);successor['rollback_authority_successor_of_product_lock_identity']=ACTIVE_ID;successor['gui_authority']['state']='ACTIVE';att=successor['activation_attestation'];att['current_activation_receipt_identity']=receipt['activation_receipt_identity'];att['current_active_state_authority_identity']=authority['active_state_authority_identity'];att['canonical_rollback_manifest_identity']=manifest['rollback_manifest_identity'];att['canonical_rollback_product_lock_identity']=IMMEDIATE_ID;att['canonical_rollback_product_lock_sha256']=IMMEDIATE_SHA;att['rollback_product_lock_sha256']=IMMEDIATE_SHA
 successor['rollback_authority_transition']={'factual_immediate_predecessor_root':IMMEDIATE_ROOT,'historical_roots':[{'root':HISTORICAL_ROOT,'classification':'HISTORICAL_NON_CANONICAL'},{'root':PRIOR_ROOT,'classification':'HISTORICAL_NON_CANONICAL_PENDING_RETIREMENT'}]}
 repl={'app/cli/preflight.py':row(repo/'scripts/vnext_gui_attestation_rollback_preflight_v1.py','app/cli/preflight.py'),'manifest/activation/vnext-activation-receipt-v1.json':row(out/'vnext-gui-current-activation-receipt-v2.json','manifest/activation/vnext-activation-receipt-v1.json'),'manifest/authorities/vnext-active-product-lock-successor-v1.json':row(out/'vnext-gui-current-active-state-authority-v2.json','manifest/authorities/vnext-active-product-lock-successor-v1.json'),'manifest/rollback/vnext-canonical-rollback-manifest-v1.json':row(out/'vnext-gui-attestation-canonical-rollback-manifest-v5.json','manifest/rollback/vnext-canonical-rollback-manifest-v1.json')}
 rows={x['path']:x for x in successor['application_files']};rows.update(repl);successor['application_files']=[rows[k] for k in sorted(rows)];write(out/'vnext-gui-attestation-rollback-product-lock-v8.json',successor,'product_lock_identity')
 return {'status':'PASS','blockers':0,'activation_receipt_identity':receipt['activation_receipt_identity'],'active_state_authority_identity':authority['active_state_authority_identity'],'rollback_manifest_identity':manifest['rollback_manifest_identity'],'product_lock_identity':successor['product_lock_identity'],'product_lock_sha256':sha(out/'vnext-gui-attestation-rollback-product-lock-v8.json'),'canonical_rollback_root':IMMEDIATE_ROOT,'historical_roots':historical_roots,'managed_replacements':sorted(repl),'voice':'DISABLED_UNTIL_PROMOTION','legacy_dependency_count':0}
if __name__=='__main__':
 p=argparse.ArgumentParser()
 for n in ('repo','active','immediate','historical','prior','out'):p.add_argument('--'+n,type=Path,required=True)
 a=p.parse_args();print(json.dumps(build(a.repo,a.active,a.immediate,a.historical,a.prior,a.out),sort_keys=True))
