#!/usr/bin/env python3
import argparse,copy,hashlib,json,types
from pathlib import Path
COMMIT='01df91cdbcb685363d2cdd05ce57af1bddc51c77';INSTALLED='6deeb96a788f3780835a9dce3583153e53ab6c6121ddea994495e4c9cc8e1a9f';INSTALLED_SHA='67dead9fd542da9464fc798a7037fb15b4c5f8270c626c9e0ce41f58265a74ff';CANDIDATE='4d45f169ed4f6eba530e181a7e61ce4ade02d63e8d21f5177b3d4d18d15a0738';GRAPH='01d6b01a382ceb21518beeed0e6c5645f076e071767096d4358ddc5aa8ea5409';SURFACE='29dddf588f38661416ee3f11fd63e66ec4673fd65cc55bb89853052a5f552dc6';AUDIT='dfb1bb619e438d9b41fbbe5e22f38e6183760e3768acea1feb057c603b91ec78';RB='/root/pastila-vnext/.rollback-pre-gui-4d45f169';RBSHA='c9c6b9bb60c881781b1b534990bc37b76a7e012f2599144e2656984854f5fa58';PRIOR='/root/pastila-vnext/.rollback-pre-contract-e180a1e5';PRIORSHA='196c5f7bdec6f59f0609ad334dbdebdc17e5ad9f793945713ff2b7afaa5b58a2'
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ident(v):return hashlib.sha256(canon(v)).hexdigest()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v,k):v.pop(k,None);v[k]=ident(v);Path(p).write_text(json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def row(p,t):p=Path(p);return {'path':t,'type':'file','size':p.stat().st_size,'sha256':sha(p)}
def build(repo,active,rollback,prior,out):
 repo,active,rollback,prior,out=map(lambda p:Path(p).resolve(),(repo,active,rollback,prior,out));cur=json.loads((active/'product-lock.json').read_text())
 if cur['product_lock_identity']!=INSTALLED or sha(active/'product-lock.json')!=INSTALLED_SHA or cur['active_graph_identity']!=GRAPH:raise RuntimeError('active identity')
 if sha(rollback/'product-lock.json')!=RBSHA or sha(prior/'product-lock.json')!=PRIORSHA:raise RuntimeError('rollback identity')
 m=types.ModuleType('ctl');p=repo/'scripts/vnext_atomic_activation_managed_mutable_v1.py';exec(compile(p.read_bytes(),str(p),'exec'),m.__dict__);surface=m.surface_snapshot(active)
 if surface['authority_identity']!=SURFACE:raise RuntimeError('surface')
 out.mkdir(parents=True,exist_ok=True)
 receipt={'schema':'vnext-gui-current-activation-receipt-v1','schema_version':1,'status':'ATTESTED_CURRENT_ACTIVATION','temporal_claim':{'activated_at':None,'status':'NOT_RECORDED_NO_RETROACTIVE_FABRICATION'},'authority_commit':COMMIT,'candidate':{'product_lock_identity':CANDIDATE},'installed_product_lock':{'identity':INSTALLED,'sha256':INSTALLED_SHA},'active_graph_identity':GRAPH,'atomic_swap':{'mechanism':'renameat2(RENAME_EXCHANGE)','result':'PASS_ACTIVATED','active_root':'/root/pastila-vnext/v1'},'active':{'authority_surface_identity':SURFACE,'audit_identity':AUDIT,'startup':'PASS_STARTUP_READY','integrated_e2e':'EXPORTED','managed_files':33},'rollback':{'immediate_root':RB,'product_lock_sha256':RBSHA,'prior_root':PRIOR,'prior_product_lock_sha256':PRIORSHA},'voice':'DISABLED_UNTIL_PROMOTION','repository_dependency_count':0,'legacy_dependency_count':0};write(out/'vnext-gui-current-activation-receipt-v1.json',receipt,'activation_receipt_identity')
 authority={'schema':'vnext-gui-current-active-state-authority-v1','schema_version':1,'status':'ACTIVATED_ATTESTED','active_root':'/root/pastila-vnext/v1','installed_product_lock':{'identity':INSTALLED,'sha256':INSTALLED_SHA},'activation_candidate_product_lock_identity':CANDIDATE,'activation_receipt_identity':receipt['activation_receipt_identity'],'active_graph_identity':GRAPH,'active_authority_surface_identity':SURFACE,'post_install_audit_identity':AUDIT,'canonical_rollback':{'root':RB,'product_lock_sha256':RBSHA},'prior_rollback':{'root':PRIOR,'product_lock_sha256':PRIORSHA},'voice':'DISABLED_UNTIL_PROMOTION','legacy_dependency_count':0};write(out/'vnext-gui-current-active-state-authority-v1.json',authority,'active_state_authority_identity')
 lock=copy.deepcopy(cur);lock['attestation_successor_of_product_lock_identity']=INSTALLED;lock['activation_attestation']['current_activation_receipt_identity']=receipt['activation_receipt_identity'];lock['activation_attestation']['current_active_state_authority_identity']=authority['active_state_authority_identity'];lock['activation_attestation']['installed_product_lock_identity']=INSTALLED;lock['activation_attestation']['active_authority_surface_identity']=SURFACE;lock['activation_attestation']['audit_identity']=AUDIT
 repl={'manifest/activation/vnext-activation-receipt-v1.json':row(out/'vnext-gui-current-activation-receipt-v1.json','manifest/activation/vnext-activation-receipt-v1.json'),'manifest/authorities/vnext-active-product-lock-successor-v1.json':row(out/'vnext-gui-current-active-state-authority-v1.json','manifest/authorities/vnext-active-product-lock-successor-v1.json')};rows={x['path']:x for x in lock['application_files']};rows.update(repl);lock['application_files']=[rows[x] for x in sorted(rows)];write(out/'vnext-gui-current-active-product-lock-v8.json',lock,'product_lock_identity')
 result={'schema':'vnext-gui-current-activation-attestation-result-v1','schema_version':1,'status':'PASS','blockers':0,'installed_product_lock_identity':INSTALLED,'activation_receipt_identity':receipt['activation_receipt_identity'],'active_state_authority_identity':authority['active_state_authority_identity'],'product_lock_successor_identity':lock['product_lock_identity'],'product_lock_successor_sha256':sha(out/'vnext-gui-current-active-product-lock-v8.json'),'active_graph_identity':GRAPH,'active_authority_surface_identity':SURFACE,'post_install_audit_identity':AUDIT,'immediate_rollback_root':RB,'prior_rollback_root':PRIOR,'voice':'DISABLED_UNTIL_PROMOTION','legacy_dependency_count':0};write(out/'vnext-gui-current-activation-attestation-result-v1.json',result,'result_identity');return result
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--repo',type=Path,required=True);p.add_argument('--active',type=Path,required=True);p.add_argument('--rollback',type=Path,required=True);p.add_argument('--prior',type=Path,required=True);p.add_argument('--out',type=Path,required=True);a=p.parse_args();print(json.dumps(build(a.repo,a.active,a.rollback,a.prior,a.out),sort_keys=True))
