#!/usr/bin/env python3
import argparse,copy,hashlib,json
from pathlib import Path
AID="f4be30b434dd4ed1f709fb1fa0115c297f599bf1acb382a40255c1ce00f7bd3e";ASHA="560994813a34a4af7522fbb1e686ce13410eb780ce06b28a0cec7d3eccd12740";RID="3ab1a7dd2694bf62466c8444492e5781a71f219ab9d26722ea9451983344962e";AAID="4d426ecf1e1909457df131d4639d95bdd56bce699eda42700c32fad050b1cdc0"
C=("/root/pastila-vnext/.rollback-pre-gui-coherent-733ad2a1","5a5988bd0fb3b7d760c5a99dd13c007281a6900dd6a572c21c3812d6cd00bf93","6c79a7e25b22c80caad93a05b6701860166e3af88626a543fc3aa9c38ed761ee")
H=[("GUI_PREDECESSOR","/root/pastila-vnext/.rollback-pre-gui-4d45f169","278df8cdd27f641a44fd7941bfc89c362dcb5af3f1a9f265148fa11c85e44ab0","c9c6b9bb60c881781b1b534990bc37b76a7e012f2599144e2656984854f5fa58","929972ebc89e54c7d7d94b87346b2faf50823608"),("CONTRACT_PREDECESSOR","/root/pastila-vnext/.rollback-pre-contract-e180a1e5","03e43da4e052ed0bf0a1caa7f9da7103a111e1192362ea9887ed86388b864b78","196c5f7bdec6f59f0609ad334dbdebdc17e5ad9f793945713ff2b7afaa5b58a2","929972ebc89e54c7d7d94b87346b2faf50823608"),("EXCHANGE_PREDECESSOR","/root/pastila-vnext/.rollback-pre-exchange-5e31722e","68fb2c347367ff3aa725cfb44de11be07921ad2e39fcbe98b01b389eee46c19b","0ff93c4d9f550c8458d2223ae91627903bf02dc24973c59d3069fa94ada1100e","a65095dc0b362fcbba6439d64cc5af4ae9d294ff")]
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":")).encode()
def ident(v):return hashlib.sha256(canon(v)).hexdigest()
def sha(p):
 h=hashlib.sha256();h.update(Path(p).read_bytes());return h.hexdigest()
def write(p,v,k):v.pop(k,None);v[k]=ident(v);p.write_text(json.dumps(v,sort_keys=True,indent=2)+"\n")
def row(p,t):return {"path":t,"type":"file","size":p.stat().st_size,"sha256":sha(p)}
def build(repo,active,roots,out):
 if [str(x) for x in roots]!=[C[0]]+[x[1] for x in H]:raise RuntimeError("root order")
 l=json.loads((active/"product-lock.json").read_text())
 if l.get("product_lock_identity")!=AID or sha(active/"product-lock.json")!=ASHA:raise RuntimeError("active")
 if json.loads((roots[0]/"product-lock.json").read_text()).get("product_lock_identity")!=C[1] or sha(roots[0]/"product-lock.json")!=C[2]:raise RuntimeError("canonical")
 for root,x in zip(roots[1:],H):
  q=json.loads((root/"product-lock.json").read_text())
  if q.get("product_lock_identity")!=x[2] or sha(root/"product-lock.json")!=x[3]:raise RuntimeError("historical")
 r0=json.loads((active/"manifest/activation/vnext-activation-receipt-v1.json").read_text());a0=json.loads((active/"manifest/authorities/vnext-active-product-lock-successor-v1.json").read_text())
 if r0.get("activation_receipt_identity")!=RID or a0.get("active_state_authority_identity")!=AAID:raise RuntimeError("authority")
 out.mkdir(parents=True,exist_ok=True)
 ev=[{"generation":g,"product_lock_identity":i,"product_lock_sha256":d,"origin_commit":c,"evidence_role":"CONTENT_ADDRESSED_PROVENANCE_ONLY","physical_root_required":False,"reconstructible":True} for g,_,i,d,c in H]
 m={"schema":"vnext-canonical-only-rollback-manifest-v8","schema_version":8,"status":"PASS_CANONICAL_ONLY_FACTUAL_IMMEDIATE_PREDECESSOR","recovery_topology":{"active":"/root/pastila-vnext/v1","canonical_rollback":C[0],"physical_root_count":1,"historical_physical_roots_required":0},"rollback_root":C[0],"authority":{"product_lock_identity":C[1],"product_lock_sha256":C[2]},"historical_evidence":ev,"legacy_dependency_count":0};write(out/"vnext-canonical-only-rollback-manifest-v8.json",m,"rollback_manifest_identity")
 r=copy.deepcopy(r0);r.pop("activation_receipt_identity",None);r.update(schema="vnext-canonical-only-current-activation-receipt-v5",schema_version=5,status="ATTESTED_CURRENT_ACTIVATION_CANONICAL_ONLY_RECOVERY",predecessor_activation_receipt_identity=RID);r["rollback"]={"canonical_root":C[0],"canonical_product_lock_identity":C[1],"canonical_product_lock_sha256":C[2],"manifest_identity":m["rollback_manifest_identity"],"historical_evidence":ev,"physical_historical_roots_required":0};write(out/"vnext-canonical-only-current-activation-receipt-v5.json",r,"activation_receipt_identity")
 a={"schema":"vnext-canonical-only-current-active-state-authority-v5","schema_version":4,"status":"ACTIVATED_ATTESTED_CANONICAL_ONLY_RECOVERY","active_root":"/root/pastila-vnext/v1","installed_product_lock":{"identity":AID,"sha256":ASHA},"predecessor_active_state_authority_identity":AAID,"activation_receipt_identity":r["activation_receipt_identity"],"active_graph_identity":l["active_graph_identity"],"active_authority_surface_identity":a0["active_authority_surface_identity"],"post_install_audit_identity":a0["post_install_audit_identity"],"canonical_rollback":{"manifest_identity":m["rollback_manifest_identity"],"root":C[0],"product_lock_identity":C[1],"product_lock_sha256":C[2]},"recovery_topology":"ACTIVE_TO_CANONICAL_ONLY","historical_evidence":ev,"voice":"DISABLED_UNTIL_PROMOTION","legacy_dependency_count":0};write(out/"vnext-canonical-only-current-active-state-authority-v5.json",a,"active_state_authority_identity")
 s=copy.deepcopy(l);s["canonical_only_recovery_successor_of_product_lock_identity"]=AID
 s["activation_attestation"].update(current_activation_receipt_identity=r["activation_receipt_identity"],current_active_state_authority_identity=a["active_state_authority_identity"],canonical_rollback_manifest_identity=m["rollback_manifest_identity"],canonical_rollback_product_lock_identity=C[1],canonical_rollback_product_lock_sha256=C[2],rollback_product_lock_sha256=C[2])
 s["rollback_authority_transition"]={"factual_immediate_predecessor_root":C[0],"topology":"ACTIVE_TO_CANONICAL_ONLY","historical_physical_roots_required":0,"historical_evidence":ev};s["historical_chain_retirement_readiness"]={"physical_path_references":0,"physical_identity_dependencies":0,"retirement_requires_further_authority_successor":False,"eligible_generations":[x[0] for x in H]}
 repl={"app/cli/preflight.py":row(repo/"scripts/vnext_canonical_only_recovery_preflight_v1.py","app/cli/preflight.py"),"manifest/activation/vnext-activation-receipt-v1.json":row(out/"vnext-canonical-only-current-activation-receipt-v5.json","manifest/activation/vnext-activation-receipt-v1.json"),"manifest/authorities/vnext-active-product-lock-successor-v1.json":row(out/"vnext-canonical-only-current-active-state-authority-v5.json","manifest/authorities/vnext-active-product-lock-successor-v1.json"),"manifest/rollback/vnext-canonical-rollback-manifest-v1.json":row(out/"vnext-canonical-only-rollback-manifest-v8.json","manifest/rollback/vnext-canonical-rollback-manifest-v1.json")}
 rows={x["path"]:x for x in s["application_files"]};rows.update(repl);s["application_files"]=[rows[k] for k in sorted(rows)];write(out/"vnext-canonical-only-product-lock-v8.json",s,"product_lock_identity")
 blob="\n".join((out/n).read_text() for n in ["vnext-canonical-only-rollback-manifest-v8.json","vnext-canonical-only-current-activation-receipt-v5.json","vnext-canonical-only-current-active-state-authority-v5.json","vnext-canonical-only-product-lock-v8.json"])
 if any(x[1] in blob for x in H):raise RuntimeError("historical path")
 return {"status":"PASS","blockers":0,"activation_receipt_identity":r["activation_receipt_identity"],"active_state_authority_identity":a["active_state_authority_identity"],"rollback_manifest_identity":m["rollback_manifest_identity"],"product_lock_identity":s["product_lock_identity"],"product_lock_sha256":sha(out/"vnext-canonical-only-product-lock-v8.json"),"canonical_rollback_root":C[0],"recovery_topology":"ACTIVE_TO_CANONICAL_ONLY","historical_physical_path_references":0,"historical_evidence":ev,"voice":"DISABLED_UNTIL_PROMOTION","legacy_dependency_count":0}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--repo",type=Path,required=True);p.add_argument("--active",type=Path,required=True);p.add_argument("--roots",type=Path,nargs=4,required=True);p.add_argument("--out",type=Path,required=True);q=p.parse_args();print(json.dumps(build(q.repo,q.active,q.roots,q.out),sort_keys=True))
