from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; ART=ROOT/'docs'/'artifacts'; P='editor-core-factual-setup-r2-t1s0-replay-protected-v1'
FILES={k:ROOT/v for k,v in {'worker':'scripts/train_editor_core_factual_setup_r2_t1s0_replay_protected_runtime_v1.py','route':'scripts/run_editor_core_factual_setup_r2_t1s0_replay_protected_runtime_v1.py','preflight':'scripts/preflight_editor_core_factual_setup_r2_t1s0_replay_protected_runtime_v1.py','smoke':'scripts/smoke_editor_core_factual_setup_r2_t1s0_replay_protected_runtime_v1.py','audit':'scripts/audit_editor_core_factual_setup_r2_t1s0_replay_protected_runtime_v1.py'}.items()}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def ident(v): return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 p=json.loads((ART/f'{P}-protocol.json').read_text('utf-8')); m=json.loads((ART/f'{P}-manifest.json').read_text('utf-8')); e=json.loads((ART/'editor-core-factual-setup-r2-causal-diagnostic-v1-evaluation.json').read_text('utf-8'))
 core={'schema':'editor-factual-setup-r2-t1s0-replay-protected-real-runtime-boundary','schema_version':1,'status':'BOUND_REAL_RUNTIME_NOT_AUTHORIZED','published_source_commit':'cc5e1894506372afca0a915a6ed202968c7b7f10','published_source_tree':'5939a9509fd54e2142de5448ad2ab3ffad697e99','protocol_identity':p['protocol_identity'],'pack_identity':m['pack_identity'],'evaluation_identity':e['evaluation_identity'],'parent':'R2_STEP_9','parent_adapter_identity':p['parent_adapter_identity'],'recipe':'S0_CONTROL','learning_rate':'0.0000005','tokenizer_sha256':'d5f6046775b112f0e2d456ee9dba450684ab964fe5c4e231599bdc6773028135','arms':['T1_S0_EXISTING_CONTROL','T1_S0_REPLAY_PROTECTED'],'seeds':[161803,271828,314159],'slots':6,'control_learning_signal_sha256':m['control_signal_sha256'],'protected_learning_signal_sha256':m['protected_signal_sha256'],'common_measurement_annotations_sha256':m['protected_signal_sha256'],'learning_measurement_separation':True,'output_isolation':'DISTINCT_EMPTY_ROOT_PER_ARM_SEED','terminal_rule':'TERMINAL_RECEIPT_LAST','files':{k:sha(v) for k,v in FILES.items()},'model_load_authorized':False,'optimizer_creation_authorized':False,'optimizer_steps_authorized':0,'training_authorized':False,'inference_authorized':False,'historical_holdouts_allowed':False,'parent_selection_authority':False,'promotion':False,'release':False}
 out={**core,'runtime_boundary_identity':ident(core)}; (ART/f'{P}-runtime-boundary.json').write_bytes((json.dumps(out,indent=2,sort_keys=True)+'\n').encode())
if __name__=='__main__': main()
