#!/usr/bin/env python3
"""Build an inactive, exact and reconstructible VNext product root candidate."""
import argparse,hashlib,json,shutil,subprocess,sys
from pathlib import Path
RUNTIME_SOURCE="c211a07551284627a8e23c6e84d7dbf7e1125681"
BOUND_PARENT="210ad63de93fbc1ce2185cee72090c23b51a07c2"
MODULES=("vnext_foundation_v1.py","vnext_workflow_v1.py","vnext_state_sqlite_v1.py","vnext_scout_production_v1.py","vnext_r2_consolidation_binding_v1.py","vnext_editor_vertical_slice_v1.py","vnext_factual_acceptance_v1.py","vnext_core_final_v1.py","vnext_product_orchestrator_v1.py")
AUTHORITIES=("vnext-active-authority-audit-manifest-v1.json","vnext-canonical-sourcepacket-v1-contract.json","vnext-consolidated-operational-state-sqlite-boundary-v7-contract.json","vnext-active-product-workflow-state-contract-v6.json","vnext-active-product-consolidation-acceptance-gates-v1.json","vnext-active-product-dependency-graph-v2.json","vnext-active-integration-platform-lock-semantics-v2.json")
CLI={"preflight_vnext_active_integration_candidate_v1.py":"preflight.py","accept_vnext_active_integration_candidate_v1.py":"acceptance.py","product_cli_vnext_v1.py":"product.py","simulate_vnext_atomic_product_root_swap_v1.py":"activation.py"}
def canonical(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()
def identity(v):return hashlib.sha256(canonical(v)).hexdigest()
def fh(p):
 h=hashlib.sha256()
 with p.open("rb") as f:
  for c in iter(lambda:f.read(8*1024*1024),b""):h.update(c)
 return h.hexdigest()
def write(p,v,key=None):
 if key:v[key]=identity(v)
 p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2).encode()+b"\n")
def copytree(a,b):b.parent.mkdir(parents=True,exist_ok=True);subprocess.run(["cp","-a",str(a),str(b)],check=True)
def build(repo,source,target,assembly_commit):
 if target.exists():raise RuntimeError("target must be new")
 if len(assembly_commit)!=40:raise RuntimeError("exact assembly commit required")
 target.mkdir(parents=True);sys.path.insert(0,str(repo/"scripts"))
 from preflight_vnext_active_integration_candidate_v1 import tree_identity
 copytree(source/"components/r2-reference-v1",target/"components/editor-r2")
 copytree(source/"platform/python-ml-v1",target/"platform/python-ml")
 pkg=target/"app/workflow/pastila_scout";pkg.mkdir(parents=True);(pkg/"__init__.py").write_text("",encoding="utf-8")
 for n in MODULES:shutil.copy2(repo/"src/pastila_scout"/n,pkg/n)
 cli=target/"app/cli";cli.mkdir(parents=True)
 for source_name,target_name in CLI.items():shutil.copy2(repo/"scripts"/source_name,cli/target_name)
 (target/"config").mkdir();shutil.copy2(source/"runtime/scout-v1/sources.json",target/"config/sources.json")
 (target/"contracts").mkdir();shutil.copy2(repo/"docs/artifacts/vnext-canonical-sourcepacket-v1-contract.json",target/"contracts/source-packet.json")
 auth=target/"manifest/authorities";auth.mkdir(parents=True)
 for n in AUTHORITIES:shutil.copy2(repo/"docs/artifacts"/n,auth/n)
 graph=json.loads((auth/"vnext-active-product-dependency-graph-v2.json").read_text())
 semantics=json.loads((auth/"vnext-active-integration-platform-lock-semantics-v2.json").read_text())
 stable=tree_identity(target/"platform/python-ml")
 platform={"schema":"vnext-platform-lock","schema_version":2,"status":"CANDIDATE_PLATFORM_CLOSURE","frozen_platform_authority_identity":semantics["frozen_platform_authority_identity"],"stable_content_identity":stable,"stable_content_identity_algorithm":semantics["stable_content_identity_algorithm"],"host_dependencies":semantics["host_dependencies"],"semantics_authority_identity":semantics["authority_identity"],"path":"platform/python-ml"}
 write(target/"manifest/platform-lock.json",platform,"lock_identity")
 sys.dont_write_bytecode=True;sys.path.insert(0,str(target/"app/workflow"))
 from pastila_scout.vnext_state_sqlite_v1 import SQLiteStateStore
 state=target/"state";state.mkdir();store=SQLiteStateStore(root=state,database=Path("product.sqlite3"),writer_identity="vnext-product-runtime-v1");store.bootstrap();shutil.rmtree(pkg/"__pycache__",ignore_errors=True)
 rows=[]
 for base in ("app","config","contracts","manifest"):
  for p in sorted((target/base).rglob("*")):
   if p.is_symlink():rows.append({"path":p.relative_to(target).as_posix(),"type":"symlink","target":p.readlink().as_posix()})
   elif p.is_file():
    if "__pycache__" in p.parts or p.suffix==".pyc":raise RuntimeError("generated bytecode in managed closure")
    rows.append({"path":p.relative_to(target).as_posix(),"type":"file","size":p.stat().st_size,"sha256":fh(p)})
 r2=json.loads((target/"components/editor-r2/dependency-lock.json").read_text())
 lock={"schema":"vnext-product-lock","schema_version":2,"status":"CANDIDATE_NOT_ACTIVATED","product_root":"/root/pastila-vnext/v1","active_integration_state":"CANDIDATE_NOT_ACTIVATED","runtime_source_commit":RUNTIME_SOURCE,"assembly_boundary_commit":assembly_commit,"assembly_bound_parent":BOUND_PARENT,"active_graph_identity":graph["authority_identity"],"platform_semantics_authority_identity":semantics["authority_identity"],"application_files":rows,"mutable_state":{"database":"state/product.sqlite3","bootstrap_sha256":fh(target/"state/product.sqlite3"),"authority":"CONTENT_ADDRESSED_RELATIONAL_STATE","runtime_files_allowed":True},"components":{"R2_REFERENCE":{"path":"components/editor-r2","lock_identity":r2["lock_identity"],"file_count":len(r2["files"]),"total_bytes":sum(x["size"] for x in r2["files"])},"PYTHON_ML_PLATFORM":{"path":"platform/python-ml","frozen_platform_authority_identity":semantics["frozen_platform_authority_identity"],"stable_content_identity":stable}},"excluded_categories":["VOICE_CANDIDATES","EVALUATION","HISTORICAL_RECEIPTS","LEGACY_RUNTIME"],"activation":{"prepared":True,"authorized":False,"full_root_atomic_swap_required":True,"product_lock_replacement":False},"legacy_dependency_count":0}
 write(target/"product-lock.json",lock,"product_lock_identity")
 return {"status":"PASS","product_lock_identity":lock["product_lock_identity"],"application_files":len(rows),"active_graph_identity":graph["authority_identity"],"platform_stable_content_identity":stable,"r2_files":len(r2["files"])}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--repo",type=Path,required=True);p.add_argument("--source-root",type=Path,required=True);p.add_argument("--target",type=Path,required=True);p.add_argument("--assembly-commit",required=True);a=p.parse_args();print(json.dumps(build(a.repo.resolve(),a.source_root.resolve(),a.target.resolve(),a.assembly_commit),sort_keys=True))
