"""Freeze V5.3.3 authority-partition integration and P10/P11/P12 audit."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; ART=ROOT/"docs/artifacts"
def can(v): return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()
def seal(n,v): return hashlib.sha256(can({"namespace":n,"value":v})).hexdigest()
def write(n,v): (ART/n).write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")

def main():
    source=(ROOT/"src/pastila_scout/humor_batch2_development_constructor_v5_3_3_integration.py").read_bytes()
    contract_core={"schema_name":"constructor-v5-3-3-single-source-authority-partition-contract","authority_counts":{"AUTHORITY_DERIVED_METADATA":39,"SURFACE_OBSERVED_EVIDENCE":17,"GENUINELY_GENERATIVE_CHOICES":1},"provider_schema":["clause"],"provider_prohibited_fields":["actor_surface","predicate_surface","patient_surface","produced_operand_surfaces","node_id","semantic_roles","affordances","causal_rule_ids","terminal_result","coordinates","observed_forms","canonical_form","alignment_rule"],"class_a":"derived once from frozen authority before invocation","class_b":"observed once from actual surface bytes and coordinates","class_c":"clause text only","release_authority":False}
    contract={**contract_core,"contract_identity":seal("B2_CONSTRUCTOR_V5_3_3_SINGLE_SOURCE_AUTHORITY_PARTITION_CONTRACT",contract_core)}; write("humor-mechanics-batch2-constructor-v5-3-3-single-source-authority-partition-contract.json",contract)
    impl=seal("B2_CONSTRUCTOR_V5_3_3_INTEGRATED_IMPLEMENTATION",{"contract_identity":contract["contract_identity"],"source_sha256":hashlib.sha256(source).hexdigest()})
    provider=seal("B2_CONSTRUCTOR_V5_3_3_CLAUSE_ONLY_PROVIDER",{"implementation_identity":impl,"schema":["clause"]})
    emitter=seal("B2_CONSTRUCTOR_V5_3_3_SURFACE_OBSERVING_EMITTER",{"implementation_identity":impl,"class_b_source":"ACTUAL_UTF8_BYTES"})
    regression_core={"schema_name":"constructor-v5-3-3-p10-p11-p12-anti-loop-regressions","invariants":{"P10_SEMANTIC_AUTHORITY":"Class A immutable; actual surface tested against frozen semantics","P11_SURFACE_EVIDENCE":"Class B from bytes/coordinates; licensed morphology aligns evidence without replacing it","P12_DETERMINISTIC_METADATA":"Class A derived once; provider cannot represent it"},"adversarial_cases":["CLASS_A_OVERRIDE_REJECTED","CLASS_B_COORDINATE_OR_FORM_REJECTED","SECOND_PROVIDER_FIELD_REJECTED","MISSING_AUTHORITY_CLOSURE_PRE_INVOCATION","STALE_CAUSAL_RULE_UNREPRESENTABLE","STALE_NODE_ROLE_AFFORDANCE_UNREPRESENTABLE","LEGACY_MIXED_TYPE_UNREACHABLE","LICENSED_ROMANIAN_ALIGNMENT_PRESERVED","MISSING_ROLE_FAILS_CLOSED","GENUINE_SEMANTIC_DRIFT_FAILS_CLOSED","PILOT05_12_PROTECTIONS_PRESERVED"]}
    regression={**regression_core,"regression_identity":seal("B2_CONSTRUCTOR_V5_3_3_P10_P11_P12_ANTI_LOOP_REGRESSIONS",regression_core)}; write("humor-mechanics-batch2-constructor-v5-3-3-p10-p11-p12-regressions.json",regression)
    audit_core={"schema_name":"constructor-v5-3-3-provider-emitter-integration-static-audit","verdict":"PASS_V5_3_3_SINGLE_SOURCE_PROVIDER_EMITTER_INTEGRATION_STATIC_AUDIT_ZERO_CONSTRUCTION_NO_RELEASE","P10_P11_P12_SHARED_BOUNDARY_VERDICT":"SHARED_EPISTEMIC_CLASS_DUPLICATION_AND_POST_HOC_RECONCILIATION_DEFECT_CONFIRMED_AND_REMOVED","FIVE_FIELD_PROVIDER_SINGLE_SOURCE_OF_TRUTH_VERDICT":"FAIL_DUPLICATED_GENERATIVE_REPRESENTATION_REMEDIATED_TO_CLAUSE_ONLY_PROVIDER","contract_identity":contract["contract_identity"],"implementation_identity":impl,"provider_identity":provider,"emitter_identity":emitter,"regression_identity":regression["regression_identity"],"counts":{"A":39,"B":17,"C":1},"cross_product":{"class_a_reconstructed_from_c":False,"class_a_overridden_by_c":False,"class_b_fabricated_from_a":False,"class_b_supplied_by_provider":False,"class_c_can_undetectably_change_a":False,"semantic_validation_compares_a_to_provider_metadata":False,"alignment_can_change_class_a_identity":False},"earliest_enforcement":{"pre_invocation":["authority closure","implementation/release/capability binding","proposition/span","topology/arity","roles/signatures/affordances","edge rules and necessity","terminal edge","denyset","alignment policy"],"post_realization_pre_emission":["material nodes and edges","semantic continuity","character and UTF-8 coordinates","observed Romanian forms","licensed alignment","terminal realization","semantic drift","placeholder/meta/instruction transfer"]},"legacy_reachability":"PASS_UNREACHABLE_FROM_V5_3_3_PROVIDER_PAYLOAD_DESERIALIZATION_AND_PUBLIC_API","additional_defect":"FIVE_FIELD_CREATIVE_SCHEMA_ALLOWED_CLAUSE_VERSUS_STRUCTURED_SURFACE_CONTRADICTION","remediation":"provider narrowed to clause only; structured forms and coordinates moved to Class B observation","known_blockers_before_next_family":[],"constructor_invocations":0,"provider_invocations":0,"emitter_invocations":0,"candidate_surfaces":0,"release_authority":False}
    audit={**audit_core,"static_audit_identity":seal("B2_CONSTRUCTOR_V5_3_3_INTEGRATION_STATIC_AUDIT",audit_core)}; write("humor-mechanics-batch2-constructor-v5-3-3-integration-static-audit.json",audit)
    summary={"verdict":audit["verdict"],"contract_identity":contract["contract_identity"],"provider_identity":provider,"emitter_identity":emitter,"combined_implementation_identity":impl,"static_audit_identity":audit["static_audit_identity"],"anti_loop_regression_identity":regression["regression_identity"],"execution_commit":subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()}; write("humor-mechanics-batch2-constructor-v5-3-3-integration-static-audit-summary.json",summary); print(json.dumps(summary,sort_keys=True))
if __name__=="__main__": main()
