"""Freeze the zero-construction V5.3.2 authority/derivability audit."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; ART=ROOT/"docs/artifacts"
def can(v): return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()
def seal(n,v): return hashlib.sha256(can({"namespace":n,"value":v})).hexdigest()
def write(name,v): (ART/name).write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")

def item(path,cls,source,supplier,comparison,discretion,earliest):
    return {"field":path,"authority_class":cls,"authoritative_source":source,"current_or_successor_supplier":supplier,"downstream_validation":comparison,"provider_discretion":discretion,"earliest_enforcement":earliest}

def main():
    A="AUTHORITY_DERIVED_METADATA"; B="SURFACE_OBSERVED_EVIDENCE"; C="GENUINELY_GENERATIVE_CHOICES"
    inventory=[]
    for field,source in {
      "source.exact_authorized_utf8":"frozen source/span","proposition.proposition_id":"frozen authority envelope","proposition.supporting_span_sha256":"frozen authority envelope","plan.node_id":"frozen typed plan","plan.actor_operand_id":"frozen typed plan","plan.predicate_id":"frozen typed plan","plan.patient_operand_id":"frozen typed plan","plan.predecessor_node_ids":"frozen typed plan","plan.introduced_operand_ids":"frozen typed plan","plan.source_provenance":"frozen typed plan","plan.nonfactual_scope":"frozen typed plan","operand.entity_identity":"frozen operand specs","operand.semantic_role_ids":"frozen operand specs","operand.affordance_ids":"frozen operand specs","operand.provenance_operand_ids":"frozen operand specs","operand.reclassification_only":"frozen operand specs","predicate.required_actor_roles":"frozen predicate signature","predicate.required_patient_roles":"frozen predicate signature","predicate.required_actor_affordances":"frozen predicate signature","predicate.required_patient_affordances":"frozen predicate signature","edge.predecessor_node_id":"frozen edge witness","edge.successor_node_id":"frozen edge witness","edge.produced_operand_id":"frozen edge witness","edge.consumed_position":"frozen edge witness","edge.explicit_licensing_rule":"frozen edge witness","edge.counterfactual_dependency":"frozen edge witness","edge.non_arbitrary":"frozen edge witness","realization.node_order":"frozen typed plan","realization.terminal_result_flag":"last frozen plan node","realization.produced_operand_ids":"frozen node introduces_ids","realization.actor_semantic_roles":"frozen actor operand spec","realization.actor_affordances":"frozen actor operand spec","realization.patient_semantic_roles":"frozen patient operand spec","realization.patient_affordances":"frozen patient operand spec","realization.predecessor_causal_rule_ids":"frozen edge witnesses","alignment.allowed_rule_set":"frozen V5.3.1 contract","release.packet_identity":"frozen release","release.implementation_identities":"frozen release","release.fragment_denyset_identity":"frozen release"}.items():
        inventory.append(item(field,A,source,"trusted deterministic boundary","derive/reference integrity only",False,"PRE_INVOCATION"))
    for field in ("surface.complete_utf8_bytes","surface.node_clause_character_span","surface.node_clause_utf8_span","surface.actor_character_span","surface.actor_utf8_span","surface.predicate_character_span","surface.predicate_utf8_span","surface.patient_character_span","surface.patient_utf8_span","surface.produced_operand_spans","surface.terminal_result_span","surface.observed_actor_form","surface.observed_predicate_form","surface.observed_patient_form","surface.coordinate_alignment_result","surface.node_edge_materialization","surface.meta_language_scan_result"):
        inventory.append(item(field,B,"actual realized surface bytes","trusted post-realization observer","coordinate-bound reproduction from bytes",False,"POST_REALIZATION_PRE_EMISSION"))
    for field in ("provider.clause_text","provider.actor_surface_choice","provider.predicate_surface_choice","provider.patient_surface_choice","provider.produced_operand_surface_choice"):
        inventory.append(item(field,C,"provider realization choice","provider","constrained against frozen semantics and observed from bytes",True,"POST_REALIZATION_PRE_EMISSION"))
    findings=[
      {"id":"DUP_A_NODE_ID","fields":["node_id"],"classification":"PROVIDER_BOUNDARY_AUTHORITY_DUPLICATION","earliest":"PRE_INVOCATION","remediation":"removed from provider schema; plan order binds node"},
      {"id":"DUP_A_ROLE_AFFORDANCE","fields":["actor_semantic_roles","actor_affordances","patient_semantic_roles","patient_affordances"],"classification":"PROVIDER_BOUNDARY_AUTHORITY_DUPLICATION","earliest":"PRE_INVOCATION","remediation":"derive from frozen operand specs"},
      {"id":"DUP_A_CAUSAL_RULE","fields":["predecessor_causal_rule_ids"],"classification":"PRE_INVOCATION_DETERMINISTIC_BLOCKER","earliest":"PRE_INVOCATION","remediation":"derive from frozen edge witnesses; Pilot 12 regression"},
      {"id":"DUP_A_TERMINAL_AND_PRODUCED_IDS","fields":["terminal_result","produced_operand_ids"],"classification":"PROVIDER_BOUNDARY_AUTHORITY_DUPLICATION","earliest":"PRE_INVOCATION","remediation":"derive from plan position and introduces_ids"},
      {"id":"DUP_A_ALIGNMENT_LABELS","fields":["canonical_form","alignment_rule"],"classification":"PROVIDER_BOUNDARY_AUTHORITY_DUPLICATION","earliest":"PRE_INVOCATION_OR_TRUSTED_ALIGNMENT","remediation":"provider cannot supply; trusted observer applies frozen licensed rules"},
      {"id":"B_COORDINATE_RECONSTRUCTION","fields":["character_coordinates","utf8_byte_coordinates","observed_surface_forms"],"classification":"POST_REALIZATION_SURFACE_EVIDENCE_DEFECT","earliest":"POST_REALIZATION_PRE_EMISSION","remediation":"derive exclusively from actual surface bytes"},
      {"id":"C_SEMANTIC_DRIFT","fields":["creative surface relations"],"classification":"LEGITIMATE_GENERATIVE_FAILURE","earliest":"POST_REALIZATION_PRE_EMISSION","remediation":"retain fail-closed semantic/causal validation"},
      {"id":"LEGACY_REACHABILITY","fields":["V5.1/V5.2/V5.3 mixed runtime structures"],"classification":"PRE_INVOCATION_DETERMINISTIC_BLOCKER","earliest":"PRE_INVOCATION","remediation":"successor entry point accepts only reduced Class C schema; legacy structures not provider-facing"},
    ]
    core={"schema_name":"constructor-v5-3-2-full-authority-derivability-audit","overall_verdict":"DUPLICATED_AUTHORITY_ANTI_PATTERN_CONFIRMED_AND_NARROWLY_REMEDIATED","principle":"Frozen authority is derived once, surface evidence is observed once, and only genuinely creative realization choices belong to the provider.","field_inventory":inventory,"inventory_counts":{A:sum(x["authority_class"]==A for x in inventory),B:sum(x["authority_class"]==B for x in inventory),C:sum(x["authority_class"]==C for x in inventory)},"duplicate_authority_findings":findings,"capability_consumption":{"metadata_only_failures_currently_possible":True,"pilot12_was_metadata_only":True,"successor_pre_invocation_checks":["plan/spec/signature/edge closure","provider creative tuple N/N coverage","produced surface arity","all Class A derivation","release and implementation binding","denyset binding"],"must_remain_post_realization":["surface spans and UTF-8 coordinates","observed lexical forms","semantic role realization","edge materialization","causal necessity","terminal realization","meta-language and collision checks"]},"known_same_family_plumbing_failure_remaining_before_pilot13":False,"zero_construction":True,"zero_release":True,"provider_invocations":0,"candidate_surfaces":0}
    audit={**core,"audit_identity":seal("B2_CONSTRUCTOR_V5_3_2_FULL_AUTHORITY_DERIVABILITY_AUDIT",core)}
    write("humor-mechanics-batch2-constructor-v5-3-2-full-authority-derivability-audit.json",audit)
    contract_core={"schema_name":"constructor-v5-3-3-authority-partition-contract","classes":[A,B,C],"provider_schema_fields":["clause","actor_surface","predicate_surface","patient_surface","produced_operand_surfaces"],"class_a_policy":"trusted derivation from frozen references only","class_b_policy":"trusted coordinate-bound observation from actual surface only","class_c_policy":"provider creative choice constrained by frozen plan"}
    contract={**contract_core,"contract_identity":seal("B2_CONSTRUCTOR_V5_3_3_AUTHORITY_PARTITION_CONTRACT",contract_core)}; write("humor-mechanics-batch2-constructor-v5-3-3-authority-partition-contract.json",contract)
    raw=(ROOT/"src/pastila_scout/humor_batch2_development_constructor_v5_3_3_authority_partition.py").read_bytes(); implementation=seal("B2_CONSTRUCTOR_V5_3_3_AUTHORITY_PARTITION_IMPLEMENTATION",{"contract_identity":contract["contract_identity"],"sha256":hashlib.sha256(raw).hexdigest()})
    reg_core={"schema_name":"constructor-v5-3-3-duplicate-authority-regressions","covered_findings":[x["id"] for x in findings],"pilot12_regression":"2570e4c944c096011041582ed9196b26c9aa759803615cf2902d8f98eb3aaa12"}; reg={**reg_core,"regression_identity":seal("B2_CONSTRUCTOR_V5_3_3_DUPLICATE_AUTHORITY_REGRESSIONS",reg_core)}; write("humor-mechanics-batch2-constructor-v5-3-3-duplicate-authority-regressions.json",reg)
    summary={"audit_identity":audit["audit_identity"],"audit_verdict":"PASS_SOURCE_ONLY_FULL_AUTHORITY_PARTITION_REMEDIATION_ZERO_CONSTRUCTION_ZERO_RELEASE","contract_identity":contract["contract_identity"],"implementation_identity":implementation,"provider_identity":seal("B2_V5_3_3_REDUCED_CREATIVE_PROVIDER",{"implementation_identity":implementation}),"emitter_identity":seal("B2_V5_3_3_AUTHORITY_PARTITIONED_EMITTER",{"implementation_identity":implementation}),"regression_identity":reg["regression_identity"],"execution_commit":subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()}; write("humor-mechanics-batch2-constructor-v5-3-2-full-authority-derivability-audit-summary.json",summary); print(json.dumps(summary,sort_keys=True))
if __name__=="__main__": main()
