"""Canonical Romanian Conversational Engine configuration."""

from pastila_scout.editor.communication import (
    DEFAULT_SPOKEN_COMMUNICATION_ENGINE,
    communication_engine_fingerprint,
    rhythm_fingerprint,
)
from pastila_scout.editor.romanian_conversation.models import (
    AcademicLanguagePolicy,
    AILanguageIndicator,
    AuthenticityState,
    BureaucraticLanguagePolicy,
    ColloquialLanguagePolicy,
    ConversationalAuthenticityModel,
    ConversationalRepairPolicy,
    FindingSeverity,
    JargonPolicy,
    LegalPrecisionPolicy,
    LexicalNaturalnessPolicy,
    LexicalReferenceEntry,
    PressLanguagePolicy,
    RegisterAcceptabilityPolicy,
    RomanianConnectorPolicy,
    RomanianConversationalEngine,
    RomanianConversationalPattern,
    RomanianConversationalPrinciple,
    RomanianConversationalRisk,
    RomanianConversationalSensitivityPolicy,
    RomanianDemonstrativePolicy,
    RomanianEllipsisPolicy,
    RomanianEmphasisPolicy,
    RomanianEntityReferencePolicy,
    RomanianRepetitionPolicy,
    RomanianRhythmRealizationPolicy,
    RomanianSatireIntegrationPolicy,
    RomanianSyntaxPolicy,
    RomanianTeleprompterRealizationPolicy,
    RomanianWordOrderPolicy,
    SlangPolicy,
    SocialRegister,
    SocialRegisterModel,
    SpokenFragmentPolicy,
    TranslatedConstructionPolicy,
)

CANONICAL_PRINCIPLE_TITLES = (
    "Romanian sounds spoken before written",
    "Authenticity differs from grammatical correctness",
    "Naturalness never excuses ambiguity",
    "Construction works on first hearing",
    "Contemporary speech precedes literary phrasing",
    "Direct construction precedes administrative construction",
    "Concrete verbs precede abstract nominalization",
    "Active phrasing preserves relevant agency",
    "Impersonal phrasing never hides responsibility",
    "Word order may follow spoken cadence",
    "Inversion remains natural clear and purposeful",
    "Ellipsis requires obvious omitted meaning",
    "Fragments may be valid spoken units",
    "Repetition may support function",
    "Unnecessary repetition remains undesirable",
    "Connectors sound spoken rather than article-like",
    "Formal transitions never simulate coherence",
    "Colloquial language remains socially credible",
    "Slang remains contextual understandable and proportionate",
    "Jargon never becomes costume",
    "Artificial informality is undesirable",
    "Unnatural translated constructions are rejected",
    "Journalistic formulas do not dominate delivery",
    "Bureaucratic formulas do not replace human language",
    "Academic framing requires necessity",
    "Legal precision remains preserved",
    "Entities shorten naturally after introduction",
    "Pronouns and demonstratives remain unambiguous",
    "Rhythm follows Romanian cadence",
    "Sarcasm integrates into the sentence",
    "Colloquial Romanian is not street caricature",
    "Sensitive stories preserve dignity",
    "Acceptability depends on context",
    "Language trends do not become automatic canon",
    "Corrections may tune but not rewrite safeguards",
    "Editor-in-Chief remains final authority",
)

SUPPORTED_GUIDANCE_DIMENSIONS = (
    "preferred_conversational_register",
    "preferred_formality_level",
    "preferred_colloquial_density",
    "preferred_slang_tolerance",
    "preferred_connector_families",
    "discouraged_connector_families",
    "preferred_word_order_tendencies",
    "preferred_inversion_tolerance",
    "preferred_ellipsis_density",
    "preferred_fragment_density",
    "preferred_repetition_density",
    "preferred_repair_density",
    "preferred_entity_reference_style",
    "preferred_demonstrative_tolerance",
    "preferred_rhetorical_question_density",
    "preferred_explanation_density",
    "preferred_post_payoff_restraint",
    "preferred_satire_integration",
    "preferred_teleprompter_complexity",
    "preferred_lexical_directness",
    "discouraged_expressions",
    "prohibited_expressions",
    "preferred_constructions",
    "context_specific_expressions",
)


def _identifier(title: str) -> str:
    return title.lower().replace("-", " ").replace(" ", "-")


def _policy(policy_type, identifier: str, features: tuple[str, ...], **extra):
    return policy_type(
        policy_id=identifier,
        supported_features=features,
        constraints=(
            "Preserve first-hearing comprehension and upstream meaning.",
            "Use only when context, Persona, Voice, Audience, and sensitivity permit.",
        ),
        review_conditions=("Review marked, ambiguous, unstable, or grave-story use.",),
        **extra,
    )


def _catalogue() -> tuple[LexicalReferenceEntry, ...]:
    values = (
        ("connector-continuation", "și atunci", "natural_connector", "accepted"),
        ("connector-contrast", "doar că", "natural_connector", "accepted"),
        ("connector-return", "revenind", "context_connector", "context_dependent"),
        ("connector-journalistic", "de menționat că", "journalistic", "discouraged"),
        (
            "bureaucratic-implementation",
            "în vederea implementării",
            "bureaucratic",
            "marked",
        ),
        ("academic-framing", "din perspectiva paradigmei", "academic", "marked"),
        ("literary-inversion", "venit-a momentul", "literary", "context_dependent"),
        ("calque-make-sense", "face sens", "translated_calque", "marked"),
        ("colloquial-neutral", "până la urmă", "colloquial", "accepted"),
        ("slang-unstable", "delulu", "unstable_slang", "requires_review"),
        ("demonstrative-neutral", "asta", "demonstrative", "context_dependent"),
        ("repair-marker", "mai exact", "repair", "accepted"),
        ("reflection-marker", "și aici rămâne întrebarea", "reflection", "accepted"),
        ("emphasis-marker", "tocmai aici", "emphasis", "accepted"),
        ("ai-filler", "este important de subliniat", "ai_associated", "discouraged"),
    )
    return tuple(
        LexicalReferenceEntry(
            entry_id=identifier,
            normalized_expression=expression,
            category=category,
            status=status,
            explanation="Bounded classification reference, not replacement wording.",
            context_rules=("Evaluate within the supplied story context.",),
            severity_when_violated=FindingSeverity.MEDIUM,
            requires_editor_review=status in {"context_dependent", "requires_review"},
            source_type="canonical_editorial_reference",
        )
        for identifier, expression, category, status in values
    )


def _patterns() -> tuple[RomanianConversationalPattern, ...]:
    categories = (
        "direct_statement",
        "delayed_subject",
        "topic_fronting",
        "consequence_fronting",
        "contrast_fronting",
        "natural_inversion",
        "conversational_ellipsis",
        "emphasis_fragment",
        "reaction_fragment",
        "conversational_repetition",
        "discourse_marker",
        "conversational_connector",
        "clarification",
        "return_to_topic",
        "seriousness_return",
        "satirical_entry",
        "colloquial_reference",
        "natural_repair",
        "reflective_close",
        "artificial_formality",
        "press_formula",
        "bureaucratic_formula",
        "academic_formula",
        "translated_calque",
        "performative_slang",
        "artificial_fragmentation",
        "overexplained_payoff",
    )
    return tuple(
        RomanianConversationalPattern(
            pattern_id=category.replace("_", "-"),
            order=order,
            title=category.replace("_", " ").title(),
            category=category,
            normalized_shape=f"<{category}>",
            conversational_function="Classify a bounded Romanian spoken construction.",
            authenticity_classification=(
                AuthenticityState.MARKED
                if category
                in {
                    "artificial_formality",
                    "press_formula",
                    "bureaucratic_formula",
                    "academic_formula",
                    "translated_calque",
                    "performative_slang",
                    "artificial_fragmentation",
                    "overexplained_payoff",
                }
                else AuthenticityState.CONTEXT_DEPENDENT
            ),
            register_compatibility=(SocialRegister.NEUTRAL_CONVERSATIONAL,),
            story_severity_compatibility=("ordinary", "serious_when_reviewed"),
            voice_compatibility=("Preserve upstream Voice boundaries.",),
            audience_compatibility=("Preserve first-hearing comprehension.",),
            positive_constraints=("Retain a clear spoken function.",),
            negative_constraints=("Do not change facts or attribution.",),
            ambiguity_risks=("Context may not support this construction.",),
            requires_editor_review=category
            in {"performative_slang", "translated_calque"},
            provenance_type="canonical_editorial_pattern",
            examples=(f"<{category}>",),
        )
        for order, category in enumerate(categories, start=1)
    )


def _ai_indicators() -> tuple[AILanguageIndicator, ...]:
    types = (
        "excessive_symmetry",
        "identical_sentence_openings",
        "connector_stacking",
        "abstract_framing",
        "overqualification",
        "overexplained_implication",
        "post_payoff_explanation",
        "artificial_rhetorical_questions",
        "generic_moral_conclusion",
        "formal_synonym_substitution",
        "unnecessary_restatement",
        "excessive_triplets",
        "fake_conversational_fillers",
        "theatrical_fragments",
        "mechanically_alternating_lengths",
        "uniform_cadence",
        "repetitive_contrast_formulas",
        "detached_satire",
        "generic_emotional_labeling",
        "vague_institutional_agency",
        "synthetic_conclusion_language",
    )
    return tuple(
        AILanguageIndicator(
            indicator_id=item.replace("_", "-"),
            indicator_type=item,
            explanation="Editorial artificiality indicator; never proof of AI authorship.",
            evidence_reference_ids=(),
            severity=FindingSeverity.LOW,
            requires_editor_review=False,
        )
        for item in types
    )


def default_romanian_conversational_engine() -> RomanianConversationalEngine:
    communication = DEFAULT_SPOKEN_COMMUNICATION_ENGINE
    catalogue = _catalogue()
    principles = tuple(
        RomanianConversationalPrinciple(
            principle_id=_identifier(title),
            order=order,
            title=title,
            statement=f"{title} as a fixed Romanian conversational constraint.",
        )
        for order, title in enumerate(CANONICAL_PRINCIPLE_TITLES, start=1)
    )
    general_features = ("contextual classification", "first-hearing comprehension")
    return RomanianConversationalEngine(
        conversational_engine_id="pastila-acida-romanian-conversational-engine",
        version="1.0.0",
        title="Pastila Acidă Romanian Conversational Engine",
        project="Pastila Acidă",
        language="Romanian",
        language_code="ro-RO",
        jurisdiction="Romania",
        primary_medium="spoken audio-video",
        primary_context="satirical current-affairs commentary",
        canonical_assumptions=(
            "The audience understands standard contemporary Romanian.",
            "Content is heard rather than studied.",
            "Natural speech is neither careless speech nor forced slang.",
            "Grammatical possibility does not guarantee conversational plausibility.",
            "Every realization remains subordinate to upstream editorial safeguards.",
        ),
        principles=principles,
        authenticity_model=ConversationalAuthenticityModel(
            model_id="romanian-conversational-authenticity",
            first_hearing_naturalness="Evaluate immediate spoken comprehension.",
            conversational_plausibility="Evaluate contemporary conversational plausibility.",
            social_plausibility="Evaluate project-specific social credibility without universality claims.",
            spoken_cadence="Evaluate Romanian cadence independently from punctuation.",
            syntactic_naturalness="Distinguish natural syntax from merely possible syntax.",
            lexical_naturalness="Distinguish contemporary use from artificial selection.",
            register_coherence="Require story-specific register coherence.",
            rhetorical_plausibility="Require a supported conversational function.",
            performance_plausibility="Require viable spoken delivery without performance notation.",
            artificiality_indicators=("synthetic symmetry", "detached phrasing"),
        ),
        register_policy=SocialRegisterModel(
            register_model_id="pastila-acida-register-policy",
            preferred_registers=(
                SocialRegister.NEUTRAL_CONVERSATIONAL,
                SocialRegister.POLISHED_CONVERSATIONAL,
                SocialRegister.INFORMAL_CONVERSATIONAL,
                SocialRegister.RESTRAINED_COLLOQUIAL,
            ),
            context_dependent_registers=(
                SocialRegister.FAMILIAR,
                SocialRegister.STREET_INFLUENCED,
                SocialRegister.FORMAL_SPOKEN,
                SocialRegister.LEGAL,
                SocialRegister.INTERNET_NATIVE,
            ),
            discouraged_registers=(
                SocialRegister.CEREMONIAL,
                SocialRegister.JOURNALISTIC,
                SocialRegister.BUREAUCRATIC,
                SocialRegister.ACADEMIC,
                SocialRegister.PERFORMATIVE_SLANG,
            ),
            prohibited_combinations=(
                "performative slang with grave protected-subject material",
            ),
            sensitivity_constraints=("Grave stories preserve dignity and restraint.",),
            audience_constraints=("Register remains understandable on first hearing.",),
            voice_compatibility=("Register cannot override Voice safeguards.",),
            persona_compatibility=("Register remains consistent with Persona.",),
            acceptability_policy=_policy(
                RegisterAcceptabilityPolicy,
                "register-acceptability",
                ("context", "audience", "speaker", "severity", "satire", "broadcast"),
            ),
        ),
        syntax_policy=_policy(
            RomanianSyntaxPolicy, "romanian-syntax", general_features
        ),
        word_order_policy=_policy(
            RomanianWordOrderPolicy,
            "romanian-word-order",
            ("neutral order", "fronting", "inversion", "clitic awareness"),
        ),
        ellipsis_policy=_policy(
            RomanianEllipsisPolicy,
            "romanian-ellipsis",
            ("subject", "verb", "object", "context-supported", "reference loss"),
        ),
        fragment_policy=_policy(
            SpokenFragmentPolicy,
            "spoken-fragments",
            ("emphasis", "reaction", "orientation", "payoff", "closure"),
        ),
        repetition_policy=_policy(
            RomanianRepetitionPolicy,
            "romanian-repetition",
            ("lexical", "entity", "rhetorical", "clarification", "callback"),
        ),
        connector_policy=_policy(
            RomanianConnectorPolicy,
            "romanian-connectors",
            ("spoken connector classification",),
            connector_families=(
                "continuation",
                "addition",
                "contrast",
                "consequence",
                "cause",
                "chronology",
                "clarification",
                "correction",
                "return",
                "reflection",
                "escalation",
                "de-escalation",
                "satire_entry",
                "seriousness_return",
                "payoff",
                "closure",
            ),
            classifications=(
                "natural_spoken",
                "neutral",
                "formal",
                "journalistic",
                "bureaucratic",
                "academic",
                "literary",
                "translated",
                "overused",
                "context_dependent",
                "prohibited",
            ),
        ),
        colloquial_policy=_policy(
            ColloquialLanguagePolicy,
            "romanian-colloquial",
            (
                "neutral colloquialism",
                "familiar wording",
                "discourse particle",
                "socially marked expression",
            ),
        ),
        slang_policy=_policy(
            SlangPolicy,
            "romanian-slang",
            (
                "established",
                "generational",
                "internet",
                "regional",
                "ephemeral",
                "performative",
            ),
        ),
        jargon_policy=_policy(
            JargonPolicy,
            "romanian-jargon",
            ("institutional", "political", "legal", "economic", "technical", "media"),
        ),
        lexical_naturalness_policy=_policy(
            LexicalNaturalnessPolicy,
            "romanian-lexical-naturalness",
            general_features,
            categories=(
                "spoken",
                "neutral",
                "formal",
                "literary",
                "archaic",
                "bureaucratic",
                "academic",
                "legal",
                "journalistic",
                "colloquial",
                "slang",
                "regionalism",
                "borrowing",
                "calque",
                "cliche",
                "ai_associated",
            ),
            reference_catalogue=catalogue,
        ),
        translated_construction_policy=_policy(
            TranslatedConstructionPolicy,
            "romanian-translated-constructions",
            ("calque", "translated syntax", "idiom", "borrowing", "emphasis pattern"),
        ),
        press_language_policy=_policy(
            PressLanguagePolicy,
            "romanian-press-language",
            (
                "article introduction",
                "headline syntax",
                "news anchor",
                "passive attribution",
                "press conclusion",
            ),
        ),
        bureaucratic_language_policy=_policy(
            BureaucraticLanguagePolicy,
            "romanian-bureaucratic-language",
            (
                "nominalization",
                "hidden responsibility",
                "procedural inflation",
                "official euphemism",
            ),
        ),
        academic_language_policy=_policy(
            AcademicLanguagePolicy,
            "romanian-academic-language",
            (
                "abstract framing",
                "qualification",
                "concept stacking",
                "essay transition",
            ),
        ),
        legal_precision_policy=_policy(
            LegalPrecisionPolicy,
            "romanian-legal-precision",
            ("legal and factual status preservation",),
            legal_states=(
                "allegation",
                "accusation",
                "investigation",
                "suspicion",
                "indictment",
                "charge",
                "trial",
                "conviction",
                "final_conviction",
                "appeal",
                "acquittal",
                "administrative_finding",
                "judicial_finding",
                "official_statement",
                "disputed_claim",
            ),
        ),
        entity_reference_policy=_policy(
            RomanianEntityReferencePolicy,
            "romanian-entity-reference",
            (
                "full reference",
                "short reference",
                "role",
                "surname",
                "institution",
                "reintroduction",
            ),
        ),
        demonstrative_policy=_policy(
            RomanianDemonstrativePolicy,
            "romanian-demonstratives",
            (
                "proximal",
                "distal",
                "neutral",
                "group",
                "dismissive",
                "ironic",
                "ambiguous",
            ),
        ),
        emphasis_policy=_policy(
            RomanianEmphasisPolicy,
            "romanian-emphasis",
            (
                "word order",
                "repetition",
                "fragment",
                "contrast",
                "stress target",
                "pause",
            ),
        ),
        rhythm_realization_policy=_policy(
            RomanianRhythmRealizationPolicy,
            "romanian-rhythm-realization",
            (
                "clause cadence",
                "length variation",
                "coordination",
                "contrast",
                "gravity",
                "closure",
            ),
            communication_rhythm_fingerprint=rhythm_fingerprint(communication.rhythm),
        ),
        repair_policy=_policy(
            ConversationalRepairPolicy,
            "romanian-conversational-repair",
            (
                "restart",
                "self-correction",
                "clarification",
                "reference repair",
                "false-start eligibility",
            ),
        ),
        satire_integration_policy=_policy(
            RomanianSatireIntegrationPolicy,
            "romanian-satire-integration",
            (
                "fact attachment",
                "contradiction attachment",
                "understatement",
                "reversal",
                "callback",
                "gravity return",
            ),
        ),
        sensitivity_policy=_policy(
            RomanianConversationalSensitivityPolicy,
            "romanian-conversational-sensitivity",
            (
                "victims",
                "minors",
                "death",
                "illness",
                "disability",
                "abuse",
                "poverty",
                "allegations",
                "vulnerable groups",
                "grief",
                "trauma",
                "emergency",
            ),
        ),
        teleprompter_realization_policy=_policy(
            RomanianTeleprompterRealizationPolicy,
            "romanian-teleprompter-realization",
            (
                "pronunciation",
                "proper-name cluster",
                "acronym",
                "number",
                "quotation",
                "clitic density",
                "backtracking",
                "breath group",
            ),
            communication_teleprompter_fingerprint=communication_engine_fingerprint(
                communication.teleprompter_cognition
            ),
        ),
        conversational_patterns=_patterns(),
        canonical_reference_catalogue=catalogue,
        ai_likeness_indicators=_ai_indicators(),
        default_risk_definitions=(
            RomanianConversationalRisk(
                risk_id="reference-ambiguity",
                risk_type="entity_ambiguity",
                severity=FindingSeverity.HIGH,
                affected_policy_identifiers=("romanian-entity-reference",),
                explanation="A conversational reference may resolve to multiple actors.",
                evidence_references=(),
                mitigation_direction="Restore an unambiguous reference without rewriting evidence.",
                blocking=True,
                requires_editor_review=False,
            ),
        ),
        correction_integration_points=("module-2-7c-correction-handoff",),
        supported_guidance_dimensions=SUPPORTED_GUIDANCE_DIMENSIONS,
        fixed_boundaries=(
            "Never generate sentences, scripts, jokes, hooks, transitions, or replacement wording.",
            "Never change facts, attribution, causality, allegation status, or legal status.",
            "Never override Persona, Philosophy, Decision, Voice, Audience, Story, or Communication safeguards.",
            "Never trivialize or target protected subjects.",
            "Never implement learning, persistence, providers, prompts, or teleprompter formatting.",
        ),
        editor_authority="The Editor-in-Chief retains final Romanian conversational authority within fixed safeguards.",
    )


DEFAULT_ROMANIAN_CONVERSATIONAL_ENGINE = default_romanian_conversational_engine()
